---
title: 'CRD 150: Quantitative Methods in Community Research'
subtitle: <h4 style="font-style:normal">Fall 2018</h4>
---

<style>
p.comment {
background-color: #DBDBDB;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: italic;
}

</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\

Welcome to the CRD 150 website!  This website complements the class [Canvas](https://login.canvas.ucdavis.edu/) site.  

On this website you will find:

* An abridged syllabus
* Assignment guidelines 
* Lab and homework assignment material

On Canvas you will find:

* A detailed syllabus
* Reading material
* Data for labs/assignments
* Project and midterm material
* Submit your homework
* Grades

\


**About the class**

This course is an introduction to the use of statistical methods and tools to uncover, understand and conceptualize patterns in data.  The empirical and theoretical emphasis will be on the community; that is, the class will give you the methodological skills to use data to better describe communities and examine community-level phenomena.  You will work with both nonspatial and spatial data from traditional (e.g. U.S. Census) and nontraditional sources (e.g. open data portals).  Specific topics covered include data acquisition, management, and presentation (graphs, tables, maps), descriptive analysis (opportunity mapping, spatial clustering), citizen science and participatory mapping, and inferential methods (multivariate regression).  Lectures will present abstract statistical concepts alongside data analysis examples motivated through real-world problems.  Labs will provide hands-on practice of the methods covered in lecture using software programs (R, QGIS, CartoDB). 

\


Website creater and maintained by [Noli Brazil](https://nbrazil.faculty.ucdavis.edu/)
