<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Lab 3: Describing your Data</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">CRD 150: Winter 2020</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="syllabus.html">Syllabus</a>
</li>
<li>
  <a href="hw_guidelines.html">Assignment Guidelines</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Labs/Assignments
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="lab1.html">Lab 1</a>
    </li>
    <li>
      <a href="lab2.html">Lab 2</a>
    </li>
    <li>
      <a href="lab3.html">Lab 3</a>
    </li>
    <li>
      <a href="lab4.html">Lab 4</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Other
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="eligible.html">Eligible Communities</a>
    </li>
    <li>
      <a href="ndata.html">Neighborhood Data Sources</a>
    </li>
    <li>
      <a href="bigopendata.html">Big and Open Data Sources</a>
    </li>
    <li>
      <a href="nhgis.html">Using NHGIS</a>
    </li>
    <li>
      <a href="policymap.html">Using PolicyMap</a>
    </li>
    <li>
      <a href="missingdata.html">Missing Data</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Lab 3: Describing your Data</h1>
<h3 class="subtitle"><h4 style="font-style:normal">
CRD 150 - Quantitative Methods in Community Research
</h4></h3>
<h4 class="author"><h4 style="font-style:normal">
Professor Noli Brazil
</h4></h4>
<h4 class="date"><h4 style="font-style:normal">
January 24, 2020
</h4></h4>

</div>


<style>
p.comment {
background-color: #DBDBDB;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: italic;
}

.figure {
   margin-top: 20px;
   margin-bottom: 20px;
}

h1.title {
  font-weight: bold;
  font-family: Arial;  
}

h2.title {
  font-family: Arial;  
}

</style>
<style type="text/css">
#TOC {
  font-size: 13px;
  font-family: Arial;
}
</style>
<p><br />
</p>
<p>In <a href="https://crd150.github.io/lab2.html">Lab 2</a>, we worked with county-level data. That is, the rows or units of observations in our data set represented counties. In this lab, we will be working with neighborhood data, using census tracts to represent neighborhoods. The broader goal, however, is to acquire skills in running descriptive statistics and creating graphs using R. Make sure you’ve read and fully understood Handout 3 as this guide tracks closely with the material presented there. This lab’s data were downloaded from <a href="https://ucdavis.policymap.com/maps">PolicyMap</a>. The objectives of the guide are as follows</p>
<ol style="list-style-type: decimal">
<li>Get familiar with Census tract data</li>
<li>Learn how to use various R functions to summarize neighborhood characteristics</li>
<li>Introduction to R graphics</li>
</ol>
<p>This lab guide follows closely and supplements the material presented in Chapters 1,3, 5 and 22 in the textbook <a href="http://r4ds.had.co.nz/index.html">R for Data Science</a> (RDS) and the class Handout 3.</p>
<p class="comment" , style="font-style:normal">
<strong>Assignment 3 is due by 11:59 pm, January 30th on Canvas.</strong> See <a href="https://crd150.github.io/hw_guidelines.html">here</a> for assignment guidelines. You must submit an <code>.Rmd</code> file and its associated <code>.html</code> file. Name the files: yourLastName_firstInitial_asgn03. For example: brazil_n_asgn03.
</p>
<div style="margin-bottom:25px;">

</div>
<div id="open-up-a-r-markdown-file" class="section level2">
<h2><strong>Open up a R Markdown file</strong></h2>
<p><br />
Download the <a href="https://raw.githubusercontent.com/crd150/data/master/labtemplate.Rmd">Lab template</a> into an appropriate folder on your hard drive (preferably, a folder named ‘Lab 3’), open it in R Studio, and type and run your code there. Change the title (“Lab 3”) and insert your name and date. Don’t change anything else inside the YAML (the stuff at the top in between the <code>---</code>). Also keep the grey chunk after the YAML. For a rundown on the use of R Markdown in labs, see <a href="https://crd150.github.io/lab1.html">Lab 1</a></p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="installing-and-loading-packages" class="section level2">
<h2><strong>Installing and loading packages</strong></h2>
<p><br />
You’ll need to install the following package in R. You only need to do it once, so if you’ve already installed this package, skip the code. Also, don’t put the <code>install.packages()</code> command in your R Markdown document. Copy and paste the code in the R Console. We’ll talk about what this package provides as its relevant functions come up in the guide.</p>
<pre class="r"><code>install.packages(&quot;GGally&quot;)</code></pre>
<p>Next, load the required packages using <code>library()</code>. Remember, you need to do this every time you run an R session, so the following code should appear at the top of your R Markdown file.</p>
<pre class="r"><code>library(tidyverse)
library(GGally)</code></pre>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="reading-in-census-tract-data" class="section level2">
<h2><strong>Reading in census tract data</strong></h2>
<p><br />
You will be working with census tract data for the cities of Sacramento, San Francisco, San Jose, and Oakland, the four largest cities in Northern California. Let’s get some practice working with data from PolicyMap, which provides Census data along with other cool and interesting neighborhood data.</p>
<p>Unlike the Census, PolicyMap does not have a user-friendly R package for downloading their data through an API. To save us time, I downloaded data from PolicyMap, cleaned the file, and uploaded it on GitHub. Let’s bring the csv file into R using <code>read_csv()</code>.</p>
<pre class="r"><code>ncal.tracts &lt;- read_csv(&quot;https://raw.githubusercontent.com/crd150/data/master/pmap_lab3.csv&quot;)
ncal.tracts</code></pre>
<p>The dataset contains tract-level median household income, percent Hispanic, percent Black, whether the tract is designated as an <a href="http://dof.ca.gov/Forecasting/Demographics/opportunity_zones/">Opportunity Zone</a> (a high-poverty neighborhood eligible for federal economic development funding), the home mortgage loan-to-income ratio (also known as the <a href="https://www.citylab.com/equity/2015/11/the-housing-boom-is-not-a-bubble/417966/">leverage ratio</a>), and whether the tract is “Majority” Hispanic (<em>phisp</em> &gt; 50%) or “Not Majority” Hispanic. In putting this data file together, data wrangling was fairly extensive. I’ve uploaded a <a href="https://crd150.github.io/policymap.html">tutorial</a> describing the steps for downloading and cleaning these data. The tutorial also provides a brief introduction to downloading data from PolicyMap. You won’t need to go through the tutorial to complete this guide and Assignment 3, but please look through it at some point as it provides some important data wrangling functions that will be relevant for your final project, especially if you are planning to use PolicyMap data.</p>
<p><br></p>
<p>Another mini lab tutorial that is important to look through (but not required for this lab or the homework) goes through how to detect and deal with <a href="https://crd150.github.io/missingdata.html">missing data</a>. Recall from Handout 2 the importance of missing data in the Data Wrangling process. I’ve cleaned this week’s data for you so you won’t have to deal with missingness, but I recommend taking a look at the missing data mini lab at some point in the near future because you will encounter missing data in future labs, assignments and potentially in your final project.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="summarizing-a-single-variable" class="section level2">
<h2><strong>Summarizing a single variable</strong></h2>
<p><br />
Recall from Handout 1 our two important data types: categorical and numeric. Let’s first summarize a numeric variable - neighborhood median household income - using some basic descriptive statistics.</p>
<div style="margin-bottom:25px;">

</div>
<div id="numeric-variables" class="section level3">
<h3><strong>Numeric variables</strong></h3>
<p><br />
We can use the function <code>summarize()</code> to calculate mean neighborhood income. The first argument inside <code>summarize()</code> is the data object <em>ncal.tracts</em> and the second argument is the function calculating the specific summary statistic, in this case <code>mean()</code>, which unsurprisingly calculates the mean of the variable you indicate in between the parentheses.</p>
<pre class="r"><code>summarize(ncal.tracts, mean(medincome))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `mean(medincome)`
##               &lt;dbl&gt;
## 1            80309.</code></pre>
<p>Does the average neighborhood income differ by city? We need to pair <code>summarize()</code> with the function <code>group_by()</code> to answer this question. The function <code>group_by()</code> tells R to run subsequent functions on the data object <em>by</em> a group characteristic (such as gender, educational attainment, or in this case, city). Let’s use our new best friend <code>%&gt;%</code>, who we met and hugged in <a href="https://crd150.github.io/lab2.html">Lab 2</a>, to accomplish this task.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(city) %&gt;%
  summarize(mean(medincome))</code></pre>
<pre><code>## # A tibble: 4 x 2
##   city          `mean(medincome)`
##   &lt;chr&gt;                     &lt;dbl&gt;
## 1 Oakland                  66706.
## 2 Sacramento               53562.
## 3 San Francisco            90985.
## 4 San Jose                 91464.</code></pre>
<p>The utility of <code>%&gt;%</code> is that it executes tasks on the same dataset using one line of continuous code. The first pipe sends <em>ncal.tracts</em> into the function <em>group_by()</em>, which tells R to group <em>ncal.tracts</em> by the variable <em>city</em>.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(city)</code></pre>
<p>How do you know the tibble is grouped? Because it tells you</p>
<center>
<div class="figure">
<img src="groupby.png" />

</div>
</center>
<p>The second pipe takes this grouped dataset and sends it into the <code>summarize()</code> command, which calculates the mean neighborhood income (by city, because the dataset is grouped by city).</p>
<p>We can calculate more than one summary statistic within <code>summarize()</code>. For example, to get the mean, median, standard deviation and interquartile range (IQR) of median income, and give column labels for the variables in the resulting summary table, we type in</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(city) %&gt;%
  summarize(incmn = mean(medincome),
            incmd = median(medincome),
            incsd = sd(medincome),
            inciqr = IQR(medincome))</code></pre>
<pre><code>## # A tibble: 4 x 5
##   city           incmn  incmd  incsd inciqr
##   &lt;chr&gt;          &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 Oakland       66706. 51691  41262. 42011 
## 2 Sacramento    53562. 48696. 24405. 28392.
## 3 San Francisco 90985. 88929  38443. 50490 
## 4 San Jose      91464. 87917  34637. 48539</code></pre>
<p><br></p>
<p>Remember from Handout 3 that the IQR is the difference between the 75th and 25th percentiles. It is a measure of spread, and more generally, an indicator of inequality. Another measure of neighborhood inequality is the 90/10 ratio. To calculate this ratio, we’ll first need to calculate the 90th and 10th percentiles using the <code>quantile()</code> command. We can do all of this inside <code>summarize()</code>. Make sure you understand what each function in the code below is doing.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(city) %&gt;%
  summarize(incmn = mean(medincome),
            incmd = median(medincome),
            incsd = sd(medincome),
            inciqr = IQR(medincome),
            p90 = quantile(medincome, p = 0.90),
            p10 = quantile(medincome, p = 0.10),
            r90.10 = p90/p10) %&gt;%
  select(-(c(p90,p10)))</code></pre>
<pre><code>## # A tibble: 4 x 6
##   city           incmn  incmd  incsd inciqr r90.10
##   &lt;chr&gt;          &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 Oakland       66706. 51691  41262. 42011    4.38
## 2 Sacramento    53562. 48696. 24405. 28392.   3.14
## 3 San Francisco 90985. 88929  38443. 50490    3.56
## 4 San Jose      91464. 87917  34637. 48539    2.74</code></pre>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="categorical-variables" class="section level3">
<h3><strong>Categorical variables</strong></h3>
<p><br />
Let’s next summarize a categorical variable. <em>oppzone</em> indicates whether a tract is designated as an <a href="https://opzones.ca.gov/">Opportunity Zone</a> neighborhood. The variable has two categories: designated and not designated as an Opportunity Zone. To get the percent of tracts that are Opportunity Zone neighborhoods, you’ll need to combine the functions <code>group_by()</code>, <code>summarize()</code> and <code>mutate()</code> using <code>%&gt;%</code>.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(oppzone) %&gt;%
  summarize(n = n()) %&gt;%
  mutate(freq = n / sum(n))</code></pre>
<pre><code>## # A tibble: 2 x 3
##   oppzone                                   n  freq
##   &lt;chr&gt;                                 &lt;int&gt; &lt;dbl&gt;
## 1 Designated Qualified Opportunity Zone    75 0.125
## 2 Not Designated                          524 0.875</code></pre>
<p>Let’s break up this chunk of code to show exactly what was done here. First, <em>ncal.tracts</em> was piped into the <code>group_by()</code> function. Next, <code>group_by(oppzone)</code> separates the neighborhoods by Opportunity Zone designation. We then used <code>summarize()</code> to count the number of neighborhoods by Opportunity Zone designation. The function to get a count is <code>n()</code>, and we saved this count in a variable named <em>n</em>. This gave us the following table.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(oppzone) %&gt;%
  summarize (n = n())</code></pre>
<pre><code>## # A tibble: 2 x 2
##   oppzone                                   n
##   &lt;chr&gt;                                 &lt;int&gt;
## 1 Designated Qualified Opportunity Zone    75
## 2 Not Designated                          524</code></pre>
<p>There are 75 neighborhoods that are designated as an Opportunity Zone. Next, this table is piped into <code>mutate()</code>, which creates a variable showing the proportion of all neighborhoods by Opportunity Zone designation. The code <code>sum(n)</code> adds the values of <em>n</em>: 524+75 = 599. We then divide the value of each <em>n</em> by this sum: 75/599 = 0.125 and 524/599 = 0.875. That yields the final frequency table.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(oppzone) %&gt;%
  summarize (n = n()) %&gt;%
  mutate(freq = n / sum(n))</code></pre>
<pre><code>## # A tibble: 2 x 3
##   oppzone                                   n  freq
##   &lt;chr&gt;                                 &lt;int&gt; &lt;dbl&gt;
## 1 Designated Qualified Opportunity Zone    75 0.125
## 2 Not Designated                          524 0.875</code></pre>
<p>We can add <em>city</em> to the <code>group_by()</code> function to disaggregate the above results by city.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(city, oppzone) %&gt;%
  summarize (n = n()) %&gt;%
  mutate(freq = n / sum(n))</code></pre>
<pre><code>## # A tibble: 8 x 4
## # Groups:   city [4]
##   city          oppzone                                   n   freq
##   &lt;chr&gt;         &lt;chr&gt;                                 &lt;int&gt;  &lt;dbl&gt;
## 1 Oakland       Designated Qualified Opportunity Zone    30 0.265 
## 2 Oakland       Not Designated                           83 0.735 
## 3 Sacramento    Designated Qualified Opportunity Zone    23 0.23  
## 4 Sacramento    Not Designated                           77 0.77  
## 5 San Francisco Designated Qualified Opportunity Zone    11 0.0558
## 6 San Francisco Not Designated                          186 0.944 
## 7 San Jose      Designated Qualified Opportunity Zone    11 0.0582
## 8 San Jose      Not Designated                          178 0.942</code></pre>
<p>Which city has the highest proportion of Opportunity Zone neighborhoods? Lowest?</p>
<div style="margin-bottom:25px;">

</div>
</div>
</div>
<div id="summarizing-two-variables" class="section level2">
<h2><strong>Summarizing two variables</strong></h2>
<p><br />
The functions we’ve gone through so far describe <strong>one</strong> variable. It is often the case that we are interested in understanding whether two variables are associated with one another.</p>
<p>Let’s go through the ways we can describe the association between: (1) two categorical variables; (2) one categorical variable and one numeric variable; and (3) two numeric variables.</p>
<div style="margin-bottom:25px;">

</div>
<div id="two-categorical-variables" class="section level3">
<h3><strong>Two categorical variables</strong></h3>
<p><br />
To summarize the relationship between two categorical variables, you’ll need to find the proportion of observations for each combination, also known as a cross tabulation. Let’s create a cross tabulation of the categorical variables <em>oppzone</em> and <em>mhisp</em>.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(oppzone, mhisp) %&gt;%
  summarize(n = n())  %&gt;%
  mutate(freq = n / sum(n))</code></pre>
<pre><code>## # A tibble: 4 x 4
## # Groups:   oppzone [2]
##   oppzone                               mhisp            n   freq
##   &lt;chr&gt;                                 &lt;chr&gt;        &lt;int&gt;  &lt;dbl&gt;
## 1 Designated Qualified Opportunity Zone Majority        16 0.213 
## 2 Designated Qualified Opportunity Zone Not Majority    59 0.787 
## 3 Not Designated                        Majority        47 0.0897
## 4 Not Designated                        Not Majority   477 0.910</code></pre>
<p>A much higher proportion of Opportunity Zone neighborhoods are Majority Hispanic (0.213) compared to non Opportunity Zone neighborhoods (0.0897).</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="one-categorical-one-numeric" class="section level3">
<h3><strong>One categorical, one numeric</strong></h3>
<p><br />
A typical way of summarizing the relationship between a categorical variable and a numeric variable is by taking the mean of the continuous variable for each level of the categorical variable. We can get the mean loan-to-income ratio for neighborhoods designated and not designated as an Opportunity Zone using the following code.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(oppzone) %&gt;%
  summarize(&quot;Mean levratio&quot; = mean(levratio))</code></pre>
<pre><code>## # A tibble: 2 x 2
##   oppzone                               `Mean levratio`
##   &lt;chr&gt;                                           &lt;dbl&gt;
## 1 Designated Qualified Opportunity Zone            3.45
## 2 Not Designated                                   3.36</code></pre>
<p>Let’s separate by city by adding <em>city</em> to the <code>group_by()</code> function.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(city, oppzone) %&gt;%
  summarize(&quot;Mean levratio&quot; = mean(levratio))</code></pre>
<pre><code>## # A tibble: 8 x 3
## # Groups:   city [4]
##   city          oppzone                               `Mean levratio`
##   &lt;chr&gt;         &lt;chr&gt;                                           &lt;dbl&gt;
## 1 Oakland       Designated Qualified Opportunity Zone            3.46
## 2 Oakland       Not Designated                                   3.30
## 3 Sacramento    Designated Qualified Opportunity Zone            3.20
## 4 Sacramento    Not Designated                                   2.99
## 5 San Francisco Designated Qualified Opportunity Zone            3.82
## 6 San Francisco Not Designated                                   3.36
## 7 San Jose      Designated Qualified Opportunity Zone            3.54
## 8 San Jose      Not Designated                                   3.53</code></pre>
<p>Does any city stick out?</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="two-numeric-variables" class="section level3">
<h3><strong>Two numeric variables</strong></h3>
<p><br />
You can summarize the relationship between two numeric variables with the correlation coefficient. To calculate the correlation coefficient, use the function <code>cor()</code>. The first two arguments in <code>cor()</code> are the two numeric variables you want to calculate the correlation for. Let’s calculate the correlation between neighborhood income and percent race, and neighborhood loan-to-income ratio and percent race. Group these correlations by city.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(city) %&gt;%
  summarize(hisp_ratio = cor(levratio,phisp), 
            blk_ratio = cor(levratio,pblk),
            hisp_inc = cor(medincome,phisp),
            blk_inc = cor(medincome,pblk))</code></pre>
<pre><code>## # A tibble: 4 x 5
##   city          hisp_ratio blk_ratio hisp_inc blk_inc
##   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1 Oakland            0.607     0.269   -0.468  -0.488
## 2 Sacramento         0.410     0.411   -0.544  -0.484
## 3 San Francisco      0.337     0.194   -0.309  -0.344
## 4 San Jose           0.607    -0.221   -0.693  -0.229</code></pre>
<p>How would you interpret these results?</p>
<div style="margin-bottom:25px;">

</div>
</div>
</div>
<div id="summarizing-variables-using-graphs" class="section level2">
<h2><strong>Summarizing variables using graphs</strong></h2>
<p><br />
Another way of summarizing neighborhood variables and their relationships is through graphs and charts. The main package for R graphing is <strong>ggplot2</strong> which is a part of the <strong>tidyverse</strong> package. The graphing function is <code>ggplot()</code> and it takes on the basic template</p>
<p><br></p>
<pre><code>ggplot(data = &lt;DATA&gt;) +
      &lt;GEOM_FUNCTION&gt;(mapping = aes(x, y)) +
      &lt;OPTIONS&gt;()</code></pre>
<p><br></p>
<ol style="list-style-type: decimal">
<li><p><code>ggplot()</code> is the base function where you specify your dataset using the <code>data = &lt;DATA&gt;</code> argument.</p></li>
<li><p>You then need to build on this base by using the plus operator <code>+</code> and <code>&lt;GEOM_FUNCTION&gt;()</code> where <code>&lt;GEOM_FUNCTION&gt;()</code> is a unique function indicating the type of graph you want to plot. Each unique function has its unique set of mapping arguments which you specify using the <code>mapping = aes()</code> argument. Charts and graphs have an x-axis, y-axis, or both. Check <a href="https://rstudio.com/wp-content/uploads/2016/11/ggplot2-cheatsheet-2.1.pdf">this</a> ggplot cheat sheet for all possible geoms.</p></li>
<li><p><code>&lt;OPTIONS&gt;()</code> are a set of functions you can specify to change the look of the graph, for example relabelling the axes or adding a title.</p></li>
</ol>
<p>Before we go through how to create the graphs described in Handout 3, let’s first get a quick sense of how <code>ggplot()</code> works. Below is code that creates a histogram</p>
<pre class="r"><code>ggplot(ncal.tracts) + 
  geom_histogram(mapping = aes(x=medincome))</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="lab3_files/figure-html/unnamed-chunk-17-1.png" /><!-- --></p>
<p><em>ncal.tracts</em> is <code>&lt;DATA&gt;</code>, <code>geom_histogram()</code> is the <code>&lt;GEOM_FUNCTION&gt;()</code>, and <code>x=medincome</code> is the variable in <em>ncal.tracts</em> we are graphing. We don’t specify a <code>y =</code> because a histogram is a one variable plot.</p>
<div style="margin-bottom:25px;">

</div>
<div id="bar-charts" class="section level3">
<h3><strong>Bar charts</strong></h3>
<p><br />
Recall from Handout 3 that we use bar charts to summarize categorical variables. Bar charts show either the number or frequency of each category. To create a bar chart, use <code>geom_bar()</code> for <code>&lt;GEOM_FUNCTION&gt;()</code>. Let’s show a bar chart of <em>oppzone</em>. We can borrow from the code we used earlier to create our <em>oppzone</em> frequency table and pipe this table directly into <code>ggplot()</code>.</p>
<pre class="r"><code>ncal.tracts %&gt;% 
  group_by(oppzone) %&gt;%
  summarize (n = n()) %&gt;%
  mutate(freq = n / sum(n))  %&gt;%
  ggplot() +
    geom_bar(mapping=aes(x=oppzone, y=freq),stat=&quot;identity&quot;) </code></pre>
<p><img src="lab3_files/figure-html/unnamed-chunk-18-1.png" /><!-- --></p>
<p>We didn’t need to specify <code>data = &lt;DATA&gt;</code> in <code>ggplot()</code> because it was piped in. Within <code>aes()</code>, we specified the categorical variable <em>oppzone</em> on the x-axis and then the proportion of neighborhoods <em>freq</em> on the y-axis. The argument <code>stat = &quot;identity&quot;</code> tells <code>ggplot()</code> to plot the exact value listed for the variable <em>freq</em>.</p>
<p>The X and Y axes labels are not so great. Remember from the Hoffman chapters, interpretable labels are important for getting your message clearly across. We can relabel the axes using the <code>xlab()</code> and <code>ylab()</code> functions, which are examples of <code>&lt;OPTIONS&gt;()</code> functions.</p>
<pre class="r"><code>ncal.tracts %&gt;% 
  group_by(oppzone) %&gt;%
  summarize (n = n()) %&gt;%
  mutate(freq = n / sum(n))  %&gt;%
  ggplot() +
    geom_bar(mapping=aes(x=oppzone, y=freq),stat=&quot;identity&quot;) +
    xlab(&quot;Opportunity Zone&quot;) +
    ylab(&quot;Proportion&quot;)</code></pre>
<p><img src="lab3_files/figure-html/unnamed-chunk-19-1.png" /><!-- --></p>
<p>We can also show a cross tabulation of two categorical variables using a bar chart. Let’s take the earlier code used to create the cross tabulation of Opportunity Zone and Majority/Not Majority Hispanic and pipe that into <code>ggplot()</code></p>
<pre class="r"><code>ncal.tracts %&gt;% 
  group_by(oppzone, mhisp) %&gt;%
  summarize(n = n())  %&gt;%
  mutate(freq = n / sum(n)) %&gt;%
  ggplot() +
    geom_bar(mapping=aes(x=oppzone,y=freq,fill=mhisp), position=&quot;dodge&quot;,stat=&quot;identity&quot;) +
    xlab(&quot;Opportunity Zone&quot;) +
    ylab(&quot;Frequency&quot;) +
    labs(fill=&quot;Hispanic Population&quot;) </code></pre>
<p><img src="lab3_files/figure-html/unnamed-chunk-20-1.png" /><!-- --></p>
<p>The only real difference between the code to create this chart and the code to create the single variable bar chart is that you add the second categorical variable <em>mhisp</em> into the argument <code>fill=</code> within <code>aes()</code>. The argument <code>position=&quot;dodge&quot;</code> puts the bars side-by-side rather than stacked (take out <code>position=&quot;dodge&quot;</code> from the above code and see what a stacked bar chart looks like. Ugly, right?). The above code also changes the legend title using the <code>&lt;OPTIONS&gt;()</code> function <code>labs()</code>. You can also add a title, subtitle and footnotes within the <code>labs()</code> function.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="histograms" class="section level3">
<h3><strong>Histograms</strong></h3>
<p><br />
Histograms are used to summarize a single numeric variable. To create a histogram, use <code>geom_histogram()</code> for <code>&lt;GEOM_FUNCTION()&gt;</code>. Let’s create a histogram of median household income.</p>
<pre class="r"><code>ggplot(ncal.tracts) + 
  geom_histogram(mapping = aes(x=medincome)) +
  xlab(&quot;Median Household Income&quot;) </code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="lab3_files/figure-html/unnamed-chunk-21-1.png" /><!-- --></p>
<p>As described earlier, because a single variable is plotted on the x-axis, we specify <code>x =</code> in <code>aes()</code> but not a <code>y =</code>.</p>
<p>The message before the plot tells us that we can use the <code>bins =</code> argument to change the number of bins used to produce the histogram. You can increase the number of bins to make the bins narrower and thus get a finer grain of detail. Let’s increase the number of bins from 30 (the default) to 50.</p>
<pre class="r"><code>ggplot(ncal.tracts) + 
  geom_histogram(mapping = aes(x=medincome), bins = 50)+
  xlab(&quot;Median Household Income&quot;) </code></pre>
<p><img src="lab3_files/figure-html/unnamed-chunk-22-1.png" /><!-- --></p>
<p>Or you can decrease the number of bins to get a broader visual summary of the shape of the variable’s distribution. Let’s decrease the number of bins to 10.</p>
<pre class="r"><code>ggplot(ncal.tracts) + 
  geom_histogram(mapping = aes(x=medincome), bins = 10)+
  xlab(&quot;Median Household Income&quot;) </code></pre>
<p><img src="lab3_files/figure-html/unnamed-chunk-23-1.png" /><!-- --></p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="boxplots" class="section level3">
<h3><strong>Boxplots</strong></h3>
<p><br />
We can use a boxplot to visually summarize the distribution of a single variable or the relationship between a categorical and numeric variable. Use <code>geom_boxplot()</code> for <code>&lt;GEOM_FUNCTION()&gt;</code> to create a boxplot. Let’s examine median household income.</p>
<pre class="r"><code>ggplot(ncal.tracts) +
     geom_boxplot(mapping = aes(y = medincome))+
    ylab(&quot;Median Household Income&quot;) </code></pre>
<p><img src="lab3_files/figure-html/unnamed-chunk-24-1.png" /><!-- --></p>
<p>Remember from Handout 3 that the points outside the whiskers represent outliers. Outliers are defined as having values that are either larger than the 75th percentile plus 1.5 times the IQR or smaller than the 25th percentile minus 1.5 times the IQR. The IQR is $55,103, the 75th percentile is $104,670 and the 25th percentile is $49,568. While we don’t see outliers at the bottom, we do see outliers at the top - these are neighborhoods with median income values greater than $104,670 + 1.5*$55,103 = $187,324.5</p>
<p>Let’s examine the distribution of median income by Opportunity Zone. Because we are examining the association between two variables, we need to specify <em>x</em> <strong>and</strong> <em>y</em> variables.</p>
<pre class="r"><code>ggplot(ncal.tracts) +
    geom_boxplot(mapping = aes(x = oppzone, y = medincome)) +
    xlab(&quot;Opportunity Zone&quot;) +
    ylab(&quot;Median Household Income&quot;) </code></pre>
<p><img src="lab3_files/figure-html/unnamed-chunk-25-1.png" /><!-- --></p>
<p>Let’s add all the data points so you can see how the boxplots are summarizing the data.</p>
<pre class="r"><code>ggplot(ncal.tracts) +
  geom_boxplot(mapping = aes(x = oppzone, y = medincome)) +
  geom_point(aes(x = oppzone, y = medincome)) +
    xlab(&quot;Opportunity Zone&quot;) +
    ylab(&quot;Median Household Income&quot;) </code></pre>
<p><img src="lab3_files/figure-html/unnamed-chunk-26-1.png" /><!-- --></p>
<p>The straight vertical line of points is ugly, right? Let’s jitter them a bit by using <code>geom_jitter()</code> rather than <code>geom_point()</code></p>
<pre class="r"><code>ggplot(ncal.tracts) +
  geom_boxplot(mapping = aes(x = oppzone, y = medincome)) +
  geom_jitter(aes(x = oppzone, y = medincome)) +
    xlab(&quot;Opportunity Zone&quot;) +
    ylab(&quot;Median Household Income&quot;) </code></pre>
<p><img src="lab3_files/figure-html/unnamed-chunk-27-1.png" /><!-- --></p>
<p>Still ugly because the points are blocking the boxes and are spread out a bit too much. Let’s make the points more opaque and limit how far the points can go above and to the side from the vertical line.</p>
<pre class="r"><code>ggplot(ncal.tracts) +
  geom_boxplot(mapping = aes(x = oppzone, y = medincome)) +
  geom_jitter(aes(x = oppzone, y = medincome), position = position_jitter(width = 0.1, height = 0), alpha = 1/5) +
    xlab(&quot;Opportunity Zone&quot;) +
    ylab(&quot;Median Household Income&quot;) </code></pre>
<p><img src="lab3_files/figure-html/unnamed-chunk-28-1.png" /><!-- --></p>
<p><br></p>
<p><a href="https://www.youtube.com/watch?v=eAfyFTzZDMM">Beautiful</a>. The argument <code>position</code> within <code>geom_jitter()</code> provides how R should place the points. <code>width</code> specifies how far left and right the points will be jittered, <code>height</code> specifies how far above and below the points will be jittered, and <code>alpha</code> specifies how light (dark) the points should be.</p>
<p>The boxplot is for all neighborhoods combined. We can use the <code>facet_wrap()</code>function to separate by city</p>
<pre class="r"><code>ggplot(ncal.tracts) +
  geom_boxplot(mapping = aes(x = oppzone, y = medincome)) +
  xlab(&quot;Opportunity Zone&quot;) +
  ylab(&quot;Median Household Income&quot;) +
  facet_wrap(~city) </code></pre>
<p><img src="lab3_files/figure-html/unnamed-chunk-29-1.png" /><!-- --></p>
<p>Note the tilde operator <code>~</code> before city.</p>
<p>The labels for <em>oppzone</em> is really long. We can change the label names (as an exercise, try this on your own) or we can create horizontal boxplots. To create horizontal boxplots, add the <code>coord_flip()</code> function at the end. Let’s also change the axes labels to make them more descriptive (remember the Hoffman chapters regarding presentable graphics).</p>
<pre class="r"><code>ggplot(ncal.tracts) +
    geom_boxplot(mapping = aes(x = oppzone, y = medincome)) +
    facet_wrap(~city) +
    ylab(&quot;Median Household Income&quot;) +
    xlab(&quot;Opportunity Zone&quot;) +
    coord_flip()</code></pre>
<p><img src="lab3_files/figure-html/unnamed-chunk-30-1.png" /><!-- --></p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="scatterplots" class="section level3">
<h3><strong>Scatterplots</strong></h3>
<p><br />
The scatterplot is the traditional graph for visualizing the association between two continuous variables. For scatterplots, we use <code>geom_point()</code> for <code>&lt;GEOM_FUNCTION&gt;()</code>. Because we are plotting two variables, we specify an <em>x</em> and <em>y</em> variable. Does median household income change with greater percent Hispanic in the neighborhood?</p>
<pre class="r"><code>ggplot(ncal.tracts) +
    geom_point(mapping = aes(x = phisp, y = medincome)) +
    xlab(&quot;Percent Hispanic&quot;) +
    ylab(&quot;Median Household Income&quot;)</code></pre>
<p><img src="lab3_files/figure-html/unnamed-chunk-31-1.png" /><!-- --></p>
<p>And for each city?</p>
<pre class="r"><code>ggplot(ncal.tracts) +
    geom_point(mapping = aes(x = phisp, y = medincome)) +
    xlab(&quot;Percent Hispanic&quot;) +
    ylab(&quot;Median Household Income&quot;) +
    facet_wrap(~city) </code></pre>
<p><img src="lab3_files/figure-html/unnamed-chunk-32-1.png" /><!-- --></p>
<p><br></p>
<p>What do these scatter plots suggest about the relationship between income and percent Hispanic across these four cities?</p>
<p><code>ggplot()</code> is a powerful function, and you can make a lot of really visually captivating graphs. You can also make maps with the function, which we’ll cover in next week’s lab. We have just scratched the surface of its functions and features. The list of all possible plots for <code>&lt;GEOM_FUNCTION&gt;()</code> can be found <a href="https://ggplot2.tidyverse.org/reference/">here</a>. You can also make your graphs really “pretty” and professional looking by altering graphing features using <code>&lt;OPTIONS()</code>, including colors, labels, titles and axes. For a list of <code>ggplot()</code> functions that alter various features of a graph, check out <a href="http://r4ds.had.co.nz/graphics-for-communication.html">Chapter 22 in RDS</a>.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="scatter-plot-matrices" class="section level3">
<h3><strong>Scatter plot matrices</strong></h3>
<p><br />
What if you wanted to summarize the relationship between multiple variables in one graphic? A scatter plot matrix can do that. This plot visualizes the bivariate relationships among several pairs of variables. The individual scatter plots are stacked such that each variable is in turn on the x-axis and on the y-axis.</p>
<p>The <code>ggpairs()</code> function, which is a part of the <strong>GGally</strong> package, creates scatter plot matrices. Let’s produce one for the variables <em>levratio</em>, <em>medincome</em>, <em>phisp</em>, and <em>pblk</em>.</p>
<pre class="r"><code>ggpairs(ncal.tracts, columns = c(&quot;levratio&quot;, &quot;medincome&quot;, &quot;phisp&quot;, &quot;pblk&quot;), 
        diag=list(continuous=&quot;barDiag&quot;))</code></pre>
<p><img src="lab3_files/figure-html/unnamed-chunk-33-1.png" /><!-- --></p>
<p><br></p>
<p>The plot shows a lot of information in a concise and compact presentation. The diagonal shows histograms of each variable, which we specify in the code using the argument <code>diag=list(continuous=&quot;barDiag&quot;)</code>. The upper diagonal shows the correlation between the variables indicated by the column and row labels. For example, the correlation between percent black and median household income is -0.442. The lower diagonal shows scatterplots.</p>
<div style="margin-bottom:25px;">

</div>
</div>
</div>
<div id="assignment-3" class="section level2">
<h2><strong>Assignment 3</strong></h2>
<p><br />
</p>
<p>Download and open the <a href="https://raw.githubusercontent.com/crd150/data/master/yourLastName_firstInitial_asgn03.Rmd">Assignment 3 R Markdown Script</a>. Any response requiring a data analysis task must be supported by code you generate to produce your result. Just examining your various objects in the “Environment” section of R Studio is insufficient—you must use scripted commands. Submit the <code>Rmd</code> and its knitted <code>html</code> files on Canvas.</p>
<p><br></p>
<ol style="list-style-type: decimal">
<li>As a comprehensive source for neighborhood data, PolicyMap allows you to examine interesting associations across different dimensions of neighborhood health and well-being. Let’s utilize this important feature by examining potential predictors of resident health in the City of Sacramento. Bring into R the dataset <a href="https://raw.githubusercontent.com/crd150/data/master/sac_health_policymap.csv">sac_health_policymap.csv</a>, which contains census-tract level data on Sacramento downloaded from PolicyMap. Consider the dataset to be cleaned and ready for analysis. A record layout of the data can be found <a href="https://raw.githubusercontent.com/crd150/data/master/assgn3_question1_codebook.txt">here</a>. Make sure any plots and tables you construct follow the design principles outlined in Hoffman.</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><p>Create an appropriate plot that shows the shape of the distribution for the variable <em>health</em>, which measures the percent of residents reporting very good to excellent health. Describe the shape of the distribution. (2 points)</p></li>
<li><p>Examine the association between <em>health</em> and the variable <em>phys</em>. Based on this examination, briefly describe the relationship between the variable <em>health</em> and <em>phys</em>. (2 points)</p></li>
<li><p>Create the appropriate plots showing the association between <em>health</em> and the following variables: <em>foodaccess</em>, <em>hburden</em>, <em>unemp</em>, and <em>medinc</em>. Based on these plots, briefly describe the relationship between <em>health</em> and the four variables. Describe any nonlinearities in the relationships. (4 points)</p></li>
</ol>
<p><br></p>
<ol start="2" style="list-style-type: decimal">
<li>The following questions investigate housing structure in Yolo County. Bring into R the dataset <a href="https://raw.githubusercontent.com/crd150/data/master/ca_border_tracts.csv">ca_border_tracts.csv</a>, which contains 2012-2016 American Community Survey (ACS) data for census tracts in California and states sharing a boundary with California (Arizona, Nevada, and Oregon). Consider the dataset to be cleaned and ready for analysis. A record layout of the data can be found <a href="https://raw.githubusercontent.com/crd150/data/master/assgn3_question2_codebook.txt">here</a>.</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><p>What is the mean, median, interquartile range, and standard deviation of the percentage of houses built since 2000 in Yolo County? (2 points)</p></li>
<li><p>What is the correlation between median household income and percentage of houses built since 2000 in Yolo County? (1 point)</p></li>
<li><p>Show a plot investigating any potential outliers in the percentage of houses built since 2000 in Yolo County. (1 point)</p></li>
<li><p>Did you find any outliers? If so, how many? What is the mean, median and standard deviation of the percentage of houses built since 2000 in Yolo County <em>without</em> these outliers? What about the correlation between median household income and percentage of houses built since 2000? (3 points)</p></li>
<li><p>Briefly comment on what you learned in this question. (1 point)</p></li>
</ol>
<p><br></p>
<ol start="3" style="list-style-type: decimal">
<li>The following questions use the same dataset from Question 2 to investigate differences across major California regions and states sharing a boundary with California. Because California is so large, we separated the state into three regions: Bay Area, Southern California, and the rest of California.</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><p>Calculate 90/10 percentile ratios for median household income for each region (Bay Area, Southern California, Other California, Arizona, Nevada, and Oregon). Which region exhibits the highest neighborhood income inequality? Lowest? (2 points)</p></li>
<li><p>What is the association between median household income and percent white, black, and Hispanic for all regions combined? Are there any specific regions that noticeably differ from these associations? If so, which ones and how do they differ? An appropriate answer to this question includes both showing your code, its results, and some text explaining your results. (2 points).</p></li>
</ol>
<hr />
<p>Website created and maintained by <a href="https://nbrazil.faculty.ucdavis.edu/">Noli Brazil</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>


</body>
</html>
