<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Professor Noli Brazil" />

<meta name="date" content="2024-01-31" />

<title>Lab 4: Exploratory Data Analysis</title>

<script src="site_libs/header-attrs-2.22/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/tabwid-1.1.3/tabwid.css" rel="stylesheet" />
<script src="site_libs/tabwid-1.1.3/tabwid.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
      .display.math{display: block; text-align: center; margin: 0.5rem auto;}
  </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">CRD 150: Winter 2024</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="syllabus.html">Syllabus</a>
</li>
<li>
  <a href="hw_guidelines.html">Assignment Guidelines</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Labs/Assignments
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="lab1.html">Lab 1</a>
    </li>
    <li>
      <a href="lab2.html">Lab 2</a>
    </li>
    <li>
      <a href="lab3.html">Lab 3</a>
    </li>
    <li>
      <a href="lab4.html">Lab 4</a>
    </li>
    <li>
      <a href="lab5.html">Lab 5</a>
    </li>
    <li>
      <a href="lab6.html">Lab 6</a>
    </li>
    <li>
      <a href="lab7.html">Lab 7</a>
    </li>
    <li>
      <a href="lab8.html">Lab 8</a>
    </li>
    <li>
      <a href="lab9.html">Lab 9</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Other
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="eligible.html">Eligible Communities</a>
    </li>
    <li>
      <a href="tips.html">R tips</a>
    </li>
    <li>
      <a href="ndata.html">Neighborhood Data Sources</a>
    </li>
    <li>
      <a href="bigopendata.html">Big and Open Data Sources</a>
    </li>
    <li>
      <a href="policymap.html">PolicyMap </a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Lab 4: Exploratory Data Analysis</h1>
<h3 class="subtitle"><font size="4">CRD 150 - Quantitative Methods in
Community Research</font></h3>
<h4 class="author">Professor Noli Brazil</h4>
<h4 class="date">January 31, 2024</h4>

</div>


<style>
p.comment {
background-color: #DBDBDB;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: normal;
}

.figure {
   margin-top: 20px;
   margin-bottom: 20px;
}

h1.title {
  font-weight: bold;
  font-family: Arial;  
}

h2.title {
  font-family: Arial;  
}

</style>
<style type="text/css">
#TOC {
  font-size: 13px;
  font-family: Arial;
}
</style>
<p><br />
</p>
<p>The goal of this lab is to acquire skills in running descriptive
statistics and creating graphs using R. Make sure you’ve read and fully
understood Handout 4 as this guide tracks closely with the material
presented there. In this lab, we will be working with census tract data
from <a href="https://ucdavis.policymap.com/maps">PolicyMap</a>. As
described in Handout 3, census tracts are the traditional measure of
neighborhoods in the United States. The objectives of the guide are as
follows</p>
<ol style="list-style-type: decimal">
<li>Learn how to use various R functions to summarize neighborhood
characteristics</li>
<li>Learn how to make presentation-ready tables of descriptive
statistics</li>
<li>Introduction to R graphics</li>
</ol>
<p>This lab guide follows closely and supplements the material presented
in Chapters 1,3, 7 and 28 in the textbook <a
href="http://r4ds.had.co.nz/index.html">R for Data Science</a> (RDS) and
the class Handout 4.</p>
<p class="comment">
<strong>Assignment 4 is due by 10:00 am, February 7th on
Canvas.</strong> See <a
href="https://crd150.github.io/hw_guidelines.html">here</a> for
assignment guidelines. You must submit an <code>.Rmd</code> file and its
associated <code>.html</code> file. Name the files:
yourLastName_firstInitial_asgn04. For example: brazil_n_asgn04.
</p>
<div style="margin-bottom:25px;">

</div>
<div id="open-up-a-r-markdown-file" class="section level2">
<h2><strong>Open up a R Markdown file</strong></h2>
<p><br />
</p>
<p>Download the <a
href="https://raw.githubusercontent.com/crd150/data/master/labtemplate.Rmd">Lab
template</a> into an appropriate folder on your hard drive (preferably,
a folder named ‘Lab 4’), open it in R Studio, and type and run your code
there. The template is also located on Canvas under Files. Change the
title (“Lab 4”) and insert your name and date. Don’t change anything
else inside the YAML (the stuff at the top in between the
<code>---</code>). Also keep the grey chunk after the YAML. For a
rundown on the use of R Markdown, see the <a
href="https://crd150.github.io/hw_guidelines.html">assignment
guidelines</a></p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="installing-and-loading-packages" class="section level2">
<h2><strong>Installing and loading packages</strong></h2>
<p><br />
</p>
<p>We will be installing two new packages in this lab. Install the
following packages. These packages will be needed to create presentation
ready tables. Remember, you only do this once, and never within your R
Markdown.</p>
<pre class="r"><code>install.packages(&quot;flextable&quot;)
install.packages(&quot;webshot&quot;)</code></pre>
<p>Load the following packages using <code>library()</code>. Remember,
you need to do this every time you run an R session, so the following
code should appear at the top of your R Markdown file.</p>
<pre class="r"><code>library(tidyverse)
library(flextable)
library(webshot)</code></pre>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="reading-in-census-tract-data" class="section level2">
<h2><strong>Reading in census tract data</strong></h2>
<p><br />
</p>
<p>You will be working with census tract data for the cities of
Sacramento, San Francisco, San Jose, and Oakland, the four largest
cities in Northern California. Let’s get some more practice working with
data from PolicyMap. To save us time, I downloaded data from PolicyMap,
cleaned the file, and uploaded it on GitHub. The data file and its
metadata are also located on Canvas in the Week 4 Lab folder under
Files. Let’s bring the csv file into R using
<code>read_csv()</code>.</p>
<pre class="r"><code>ncal.tracts &lt;- read_csv(&quot;https://raw.githubusercontent.com/crd150/data/master/pmap_lab3.csv&quot;)</code></pre>
<p>Make sure you take a look at any dataset you bring into R.</p>
<pre class="r"><code>glimpse(ncal.tracts)</code></pre>
<pre><code>## Rows: 599
## Columns: 8
## $ fips      &lt;dbl&gt; 6067005205, 6067007204, 6067009601, 6067007106, 6067005301, …
## $ oppzone   &lt;chr&gt; &quot;Designated Qualified Opportunity Zone&quot;, &quot;Designated Qualifi…
## $ city      &lt;chr&gt; &quot;Sacramento&quot;, &quot;Sacramento&quot;, &quot;Sacramento&quot;, &quot;Sacramento&quot;, &quot;Sac…
## $ levratio  &lt;dbl&gt; 2.280000, 3.220000, 3.450000, 2.750000, 3.367861, 2.990000, …
## $ medincome &lt;dbl&gt; 30585, 56806, 52750, 98056, 12355, 61061, 41614, 30309, 5137…
## $ phisp     &lt;dbl&gt; 0.23168831, 0.25734355, 0.29462923, 0.25339747, 0.34152140, …
## $ pblk      &lt;dbl&gt; 0.09298701, 0.10451256, 0.21833995, 0.10547204, 0.30427892, …
## $ mhisp     &lt;chr&gt; &quot;Not Majority&quot;, &quot;Not Majority&quot;, &quot;Not Majority&quot;, &quot;Not Majorit…</code></pre>
<p>The dataset contains tract-level median household income, percent
Hispanic, percent Black, whether the tract is designated as an <a
href="https://opzones.ca.gov/">Opportunity Zone</a> (a high-poverty
neighborhood eligible for federal economic development funding), the
home mortgage loan-to-income ratio (also known as the <a
href="https://www.citylab.com/equity/2015/11/the-housing-boom-is-not-a-bubble/417966/">leverage
ratio</a>), and whether the tract is “Majority” Hispanic (<em>phisp</em>
&gt; 50%) or “Not Majority” Hispanic. Make sure you explore PolicyMap on
your own, as it offers a wealth of data that may be useful for your
final projects. Check the PolicyMap <a
href="https://crd150.github.io/policymap.html">tutorial</a> for steps to
downloading and cleaning PolicyMap data.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="summarizing-a-single-variable" class="section level2">
<h2><strong>Summarizing a single variable</strong></h2>
<p><br />
</p>
<p>Recall from Handout 4 our two important data types: categorical and
numeric. Let’s first summarize a single numeric variable - neighborhood
median household income - using some basic descriptive statistics.</p>
<div style="margin-bottom:25px;">

</div>
<div id="numeric-variables" class="section level3">
<h3><strong>Numeric variables</strong></h3>
<p><br />
</p>
<p>We can use the function <code>summarize()</code> to calculate mean
neighborhood income. The first argument inside <code>summarize()</code>
is the data object <em>ncal.tracts</em> and the second argument is the
function calculating the specific summary statistic, in this case
<code>mean()</code>, which unsurprisingly calculates the mean of the
variable you indicate in between the parentheses.</p>
<pre class="r"><code>ncal.tracts %&gt;%
      summarize(mean(medincome))</code></pre>
<pre><code>## # A tibble: 1 × 1
##   `mean(medincome)`
##               &lt;dbl&gt;
## 1                NA</code></pre>
<p>We get the value <em>NA</em>, which as we learned in <a
href="https://crd150.github.io/lab3.html#Missing_data">Lab 3</a>
represents a missing value. If a variable has missing values, functions
like <code>mean()</code> will return an <code>NA</code>. If we use the
function <code>summary()</code>, we find that <em>medincome</em> has 8
tracts with missing median income values</p>
<pre class="r"><code>summary(ncal.tracts)</code></pre>
<pre><code>##       fips             oppzone              city              levratio    
##  Min.   :6.001e+09   Length:599         Length:599         Min.   :2.050  
##  1st Qu.:6.067e+09   Class :character   Class :character   1st Qu.:3.140  
##  Median :6.075e+09   Mode  :character   Mode  :character   Median :3.368  
##  Mean   :6.063e+09                                         Mean   :3.368  
##  3rd Qu.:6.086e+09                                         3rd Qu.:3.570  
##  Max.   :6.086e+09                                         Max.   :5.460  
##                                                                           
##    medincome          phisp             pblk            mhisp          
##  Min.   : 12171   Min.   :0.0000   Min.   :0.00000   Length:599        
##  1st Qu.: 49690   1st Qu.:0.1039   1st Qu.:0.01798   Class :character  
##  Median : 77188   Median :0.1944   Median :0.04365   Mode  :character  
##  Mean   : 80407   Mean   :0.2447   Mean   :0.09279                     
##  3rd Qu.:104670   3rd Qu.:0.3411   3rd Qu.:0.11576                     
##  Max.   :211442   Max.   :0.8172   Max.   :0.63884                     
##  NA&#39;s   :8</code></pre>
<p>In order to calculate the mean (or any numeric descriptive statistic)
for a variable with missing values, use the argument
<code>na.rm = TRUE</code>, which will calculate the mean of the variable
without the missing values.</p>
<pre class="r"><code>summarize(ncal.tracts, mean(medincome, na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 1 × 1
##   `mean(medincome, na.rm = TRUE)`
##                             &lt;dbl&gt;
## 1                          80407.</code></pre>
<p>Does the average neighborhood income differ by city? We need to pair
<code>summarize()</code> with the function <code>group_by()</code> to
answer this question. The function <code>group_by()</code> tells R to
run subsequent functions on the data object <em>by</em> a group
characteristic (such as gender, educational attainment, or in this case,
city). Let’s use our new best friend <code>%&gt;%</code>, who we met in
<a href="https://crd150.github.io/lab2.html#Pipes">Lab 2</a>, to
accomplish this task.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(city) %&gt;%
  summarize(mean(medincome, na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 4 × 2
##   city          `mean(medincome, na.rm = TRUE)`
##   &lt;chr&gt;                                   &lt;dbl&gt;
## 1 Oakland                                66559.
## 2 Sacramento                             53798.
## 3 San Francisco                          91052.
## 4 San Jose                               91805.</code></pre>
<p>The first pipe sends <em>ncal.tracts</em> into the function
<em>group_by()</em>, which tells R to group <em>ncal.tracts</em> by the
variable <em>city</em>.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(city)</code></pre>
<p>How do you know the tibble is grouped? Because it tells you</p>
<p><br></p>
<center>
<p><img
src="groupby.png" /></p>
</center>
<p><br></p>
<p>The second pipe takes this grouped dataset and sends it into the
<code>summarize()</code> command, which calculates the mean neighborhood
income (by city, because the dataset is grouped by city).</p>
<p>We can calculate more than one summary statistic within
<code>summarize()</code>. For example, to get the mean, median, standard
deviation and interquartile range (IQR) of median income, and give
column labels for the variables in the resulting summary table, we type
in</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(city) %&gt;%
  summarize(Mean = mean(medincome,  na.rm = TRUE),
            Median = median(medincome, na.rm = TRUE),
            SD = sd(medincome,  na.rm = TRUE),
            IQR = IQR(medincome,  na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 4 × 5
##   city            Mean Median     SD    IQR
##   &lt;chr&gt;          &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 Oakland       66559. 51438. 41417. 40686.
## 2 Sacramento    53798. 49552  24415. 28390.
## 3 San Francisco 91052. 89184. 37913. 50444 
## 4 San Jose      91805. 88299  34650. 48412.</code></pre>
<p><br></p>
<p>Remember from Handout 4 that the IQR is the difference between the
75th and 25th percentiles. It is a measure of spread, and more
generally, an indicator of inequality. Another measure of spread or
inequality is the 90/10 ratio. To calculate this ratio, we’ll first need
to calculate the 90th and 10th percentiles using the
<code>quantile()</code> command, where we indicate the percentile using
the argument <code>p =</code>. We can do all of this inside
<code>summarize()</code>. Make sure you understand what each function in
the code below is doing.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(city) %&gt;%
  summarize(p90 = quantile(medincome, p = 0.90,  na.rm = TRUE),
            p10 = quantile(medincome, p = 0.10,  na.rm = TRUE),
            Ratio9010 = p90/p10) %&gt;%
  select(-(c(p90,p10)))</code></pre>
<pre><code>## # A tibble: 4 × 2
##   city          Ratio9010
##   &lt;chr&gt;             &lt;dbl&gt;
## 1 Oakland            4.39
## 2 Sacramento         3.15
## 3 San Francisco      3.49
## 4 San Jose           2.73</code></pre>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="categorical-variables" class="section level3">
<h3><strong>Categorical variables</strong></h3>
<p><br />
</p>
<p>Let’s next summarize a single categorical variable. <em>oppzone</em>
indicates whether a tract is designated as an <a
href="https://opzones.ca.gov/">Opportunity Zone</a> neighborhood. The
variable has two categories: designated and not designated as an
Opportunity Zone.</p>
<p>To get the proportion of tracts that are Opportunity Zone
neighborhoods, you’ll need to combine the functions
<code>group_by()</code>, <code>summarize()</code> and
<code>mutate()</code> using <code>%&gt;%</code>.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(oppzone) %&gt;%
  summarize(n = n()) %&gt;%
  mutate(total = sum(n),
        freq = n / total)</code></pre>
<pre><code>## # A tibble: 2 × 4
##   oppzone                                   n total  freq
##   &lt;chr&gt;                                 &lt;int&gt; &lt;int&gt; &lt;dbl&gt;
## 1 Designated Qualified Opportunity Zone    75   599 0.125
## 2 Not Designated                          524   599 0.875</code></pre>
<p>Let’s break up this chunk of code to show exactly what was done here.
First, <em>ncal.tracts</em> was piped into the <code>group_by()</code>
function. Next, <code>group_by(oppzone)</code> separates the
neighborhoods by Opportunity Zone designation. We then used
<code>summarize()</code> to count the number of neighborhoods by
Opportunity Zone designation. The function to get a count is
<code>n()</code>, and we saved this count in a variable named
<em>n</em>. This gave us the following table.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(oppzone) %&gt;%
  summarize (n = n())</code></pre>
<pre><code>## # A tibble: 2 × 2
##   oppzone                                   n
##   &lt;chr&gt;                                 &lt;int&gt;
## 1 Designated Qualified Opportunity Zone    75
## 2 Not Designated                          524</code></pre>
<p>Remember, we are trying to get the proportion of neighborhoods that
are and are not designated as Opportunity zones. This means we need a
numerator - the number of neighborhoods that are and are not designated
as Opportunity Zones. This is what <code>n = n()</code> gives us. There
are 75 neighborhoods that are designated as an Opportunity Zone.</p>
<p>Next, this table is piped into <code>mutate()</code>, which creates a
variable <em>total</em> which gives you the denominator - the total
number of neighborhoods. The code <code>sum(n)</code> adds the values of
<em>n</em>: 524+75 = 599. We then create a variable <em>freq</em>, which
divides the value of each <em>n</em> by this sum: 75/599 = 0.125 and
524/599 = 0.875. This yields the proportion of all neighborhoods by
Opportunity Zone designation (how would you transform this to a
percentage?).</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(oppzone) %&gt;%
  summarize (n = n()) %&gt;%
    mutate(total = sum(n),
        freq = n / total)</code></pre>
<pre><code>## # A tibble: 2 × 4
##   oppzone                                   n total  freq
##   &lt;chr&gt;                                 &lt;int&gt; &lt;int&gt; &lt;dbl&gt;
## 1 Designated Qualified Opportunity Zone    75   599 0.125
## 2 Not Designated                          524   599 0.875</code></pre>
<p>We can add <em>city</em> to the <code>group_by()</code> function to
disaggregate the above result by city.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(city, oppzone) %&gt;%
  summarize (n = n()) %&gt;%
    mutate(total = sum(n),
        freq = n / total)</code></pre>
<pre><code>## # A tibble: 8 × 5
## # Groups:   city [4]
##   city          oppzone                                   n total   freq
##   &lt;chr&gt;         &lt;chr&gt;                                 &lt;int&gt; &lt;int&gt;  &lt;dbl&gt;
## 1 Oakland       Designated Qualified Opportunity Zone    30   113 0.265 
## 2 Oakland       Not Designated                           83   113 0.735 
## 3 Sacramento    Designated Qualified Opportunity Zone    23   100 0.23  
## 4 Sacramento    Not Designated                           77   100 0.77  
## 5 San Francisco Designated Qualified Opportunity Zone    11   197 0.0558
## 6 San Francisco Not Designated                          186   197 0.944 
## 7 San Jose      Designated Qualified Opportunity Zone    11   189 0.0582
## 8 San Jose      Not Designated                          178   189 0.942</code></pre>
<p>Which city has the highest proportion of Opportunity Zone
neighborhoods? Lowest?</p>
<div style="margin-bottom:25px;">

</div>
</div>
</div>
<div id="summarizing-two-variables" class="section level2">
<h2><strong>Summarizing two variables</strong></h2>
<p><br />
</p>
<p>The functions we’ve gone through so far describe <strong>one</strong>
variable. It is often the case that we are interested in understanding
whether two variables are associated with one another.</p>
<p>Let’s go through the ways we can describe the association between:
(1) two categorical variables; (2) one categorical variable and one
numeric variable; and (3) two numeric variables.</p>
<div style="margin-bottom:25px;">

</div>
<div id="two-categorical-variables" class="section level3">
<h3><strong>Two categorical variables</strong></h3>
<p><br />
</p>
<p>To summarize the relationship between two categorical variables,
you’ll need to find the proportion of observations for each combination,
also known as a cross tabulation. Let’s create a cross tabulation of the
categorical variables <em>oppzone</em> and <em>mhisp</em>. We do this by
using both variables in the <code>group_by()</code> command.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(oppzone, mhisp) %&gt;%
  summarize(n = n())  %&gt;%
    mutate(total = sum(n),
        freq = n / total)</code></pre>
<pre><code>## # A tibble: 4 × 5
## # Groups:   oppzone [2]
##   oppzone                               mhisp            n total   freq
##   &lt;chr&gt;                                 &lt;chr&gt;        &lt;int&gt; &lt;int&gt;  &lt;dbl&gt;
## 1 Designated Qualified Opportunity Zone Majority        16    75 0.213 
## 2 Designated Qualified Opportunity Zone Not Majority    59    75 0.787 
## 3 Not Designated                        Majority        47   524 0.0897
## 4 Not Designated                        Not Majority   477   524 0.910</code></pre>
<p>A much higher proportion of Opportunity Zone neighborhoods are
Majority Hispanic (0.213) compared to non Opportunity Zone neighborhoods
(0.0897).</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="one-categorical-one-numeric" class="section level3">
<h3><strong>One categorical, one numeric</strong></h3>
<p><br />
</p>
<p>A typical way of summarizing the relationship between a categorical
variable and a numeric variable is to take the mean of the numeric
variable for each level of the categorical variable. We can get the mean
median household income for neighborhoods designated and not designated
as an Opportunity Zone using the following code.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(oppzone) %&gt;%
  summarize(&quot;Mean Income&quot; = mean(medincome, na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 2 × 2
##   oppzone                               `Mean Income`
##   &lt;chr&gt;                                         &lt;dbl&gt;
## 1 Designated Qualified Opportunity Zone        40694.
## 2 Not Designated                               86003.</code></pre>
<p>Let’s separate by city by adding <em>city</em> to the
<code>group_by()</code> function.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(city, oppzone) %&gt;%
  summarize(&quot;Mean Income&quot; = mean(medincome, na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 8 × 3
## # Groups:   city [4]
##   city          oppzone                               `Mean Income`
##   &lt;chr&gt;         &lt;chr&gt;                                         &lt;dbl&gt;
## 1 Oakland       Designated Qualified Opportunity Zone        36980.
## 2 Oakland       Not Designated                               77380.
## 3 Sacramento    Designated Qualified Opportunity Zone        33468.
## 4 Sacramento    Not Designated                               59606.
## 5 San Francisco Designated Qualified Opportunity Zone        53810 
## 6 San Francisco Not Designated                               93291.
## 7 San Jose      Designated Qualified Opportunity Zone        53305.
## 8 San Jose      Not Designated                               93993.</code></pre>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="two-numeric-variables" class="section level3">
<h3><strong>Two numeric variables</strong></h3>
<p><br />
</p>
<p>You can summarize the relationship between two numeric variables with
the correlation coefficient. To calculate the correlation coefficient,
use the function <code>cor()</code>. The first two arguments in
<code>cor()</code> are the two numeric variables you want to calculate
the correlation for. Let’s calculate the correlation between
neighborhood income and percent race, and neighborhood loan-to-income
ratio and percent black. Note that the argument
<code>use = "complete.obs"</code> removes the missing values in
<em>medincome</em>.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  summarize(blk_inc = cor(medincome,pblk, use = &quot;complete.obs&quot;))</code></pre>
<pre><code>## # A tibble: 1 × 1
##   blk_inc
##     &lt;dbl&gt;
## 1  -0.445</code></pre>
<p>Group these correlations by city.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(city) %&gt;%
  summarize(blk_inc = cor(medincome,pblk, use = &quot;complete.obs&quot;))</code></pre>
<pre><code>## # A tibble: 4 × 2
##   city          blk_inc
##   &lt;chr&gt;           &lt;dbl&gt;
## 1 Oakland        -0.487
## 2 Sacramento     -0.490
## 3 San Francisco  -0.340
## 4 San Jose       -0.236</code></pre>
<p>Make sure you understand what these values mean (see Handout 4).</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="tables-for-presentation" class="section level3">
<h3><strong>Tables for presentation</strong></h3>
<p><br />
</p>
<p>The output from the descriptive statistics we’ve ran so far is not
presentation ready. For example, taking a screenshot of the following
results table produces unnecessary information that is confusing and
messy.</p>
<pre class="r"><code>ncal.tracts %&gt;%
  group_by(city) %&gt;%
  summarize(Mean = mean(medincome,  na.rm = TRUE),
            Median = median(medincome, na.rm = TRUE),
            SD = sd(medincome,  na.rm = TRUE),
            IQR = IQR(medincome,  na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 4 × 5
##   city            Mean Median     SD    IQR
##   &lt;chr&gt;          &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
## 1 Oakland       66559. 51438. 41417. 40686.
## 2 Sacramento    53798. 49552  24415. 28390.
## 3 San Francisco 91052. 89184. 37913. 50444 
## 4 San Jose      91805. 88299  34650. 48412.</code></pre>
<p>Furthermore, you would like to show a table, say, in your final
project that does not require you to take a screenshot, but instead can
be produced via code, that way it can be fixed if there is an issue, and
is reproducible.</p>
<p>One way of producing presentation tables in R is through the
<strong>flextable</strong> package. First, before creating any table,
run the following code to ensure that the tables you save will have a
transparent or white background (the default is gray).</p>
<pre class="r"><code>set_flextable_defaults(background.color = &quot;white&quot;)</code></pre>
<p>Next, you will need to save the tibble or data frame of results into
an object. For example, let’s save the above results into an object
named <em>ncal.summary</em></p>
<pre class="r"><code>ncal.summary &lt;- ncal.tracts %&gt;%
  group_by(city) %&gt;%
  summarize(Mean = mean(medincome,  na.rm = TRUE),
            Median = median(medincome, na.rm = TRUE),
            SD = sd(medincome,  na.rm = TRUE),
            IQR = IQR(medincome,  na.rm = TRUE))</code></pre>
<p>You then input the object into the function <code>flextable()</code>.
Save it into an object called <em>my_table</em></p>
<pre class="r"><code>my_table &lt;- flextable(ncal.summary)</code></pre>
<p>If you type in <em>my_table</em> in the console, you should see a
relatively clean table pop up in the Viewer window. We can progressively
pipe the <em>my_table</em> object through <strong>flextable</strong>
formatting functions. For example, you can change the column header
names using the function <code>set_header_labels()</code> and center the
header names using the function <code>align()</code></p>
<pre class="r"><code>my_table &lt;- my_table %&gt;%
          set_header_labels(
            city = &quot;City&quot;,
            Mean = &quot;Mean&quot;,
            Median = &quot;Median&quot;,
            SD = &quot;Standard Deviation&quot;,
            IQR = &quot;IQR&quot;) %&gt;%
  colformat_double(digits = 1) %&gt;%
  align(align = &quot;center&quot;)

my_table</code></pre>
<div class="tabwid"><style>.cl-8e93468c{}.cl-8e8797d8{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-8e8e7134{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-8e8e713e{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-8e8e7148{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-8e8e8ab6{width:0.75in;background-color:rgba(255, 255, 255, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8e8e8ac0{width:0.75in;background-color:rgba(255, 255, 255, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8e8e8ac1{width:0.75in;background-color:rgba(255, 255, 255, 1.00);vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-8e8e8ac2{width:0.75in;background-color:rgba(255, 255, 255, 1.00);vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-8e93468c'><thead><tr style="overflow-wrap:break-word;"><th class="cl-8e8e8ab6"><p class="cl-8e8e7134"><span class="cl-8e8797d8">City</span></p></th><th class="cl-8e8e8ac0"><p class="cl-8e8e713e"><span class="cl-8e8797d8">Mean</span></p></th><th class="cl-8e8e8ac0"><p class="cl-8e8e713e"><span class="cl-8e8797d8">Median</span></p></th><th class="cl-8e8e8ac0"><p class="cl-8e8e713e"><span class="cl-8e8797d8">Standard Deviation</span></p></th><th class="cl-8e8e8ac0"><p class="cl-8e8e713e"><span class="cl-8e8797d8">IQR</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-8e8e8ac1"><p class="cl-8e8e7148"><span class="cl-8e8797d8">Oakland</span></p></td><td class="cl-8e8e8ac1"><p class="cl-8e8e7148"><span class="cl-8e8797d8">66,558.9</span></p></td><td class="cl-8e8e8ac1"><p class="cl-8e8e7148"><span class="cl-8e8797d8">51,437.5</span></p></td><td class="cl-8e8e8ac1"><p class="cl-8e8e7148"><span class="cl-8e8797d8">41,417.3</span></p></td><td class="cl-8e8e8ac1"><p class="cl-8e8e7148"><span class="cl-8e8797d8">40,686.5</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-8e8e8ac1"><p class="cl-8e8e7148"><span class="cl-8e8797d8">Sacramento</span></p></td><td class="cl-8e8e8ac1"><p class="cl-8e8e7148"><span class="cl-8e8797d8">53,797.9</span></p></td><td class="cl-8e8e8ac1"><p class="cl-8e8e7148"><span class="cl-8e8797d8">49,552.0</span></p></td><td class="cl-8e8e8ac1"><p class="cl-8e8e7148"><span class="cl-8e8797d8">24,414.8</span></p></td><td class="cl-8e8e8ac1"><p class="cl-8e8e7148"><span class="cl-8e8797d8">28,390.5</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-8e8e8ac1"><p class="cl-8e8e7148"><span class="cl-8e8797d8">San Francisco</span></p></td><td class="cl-8e8e8ac1"><p class="cl-8e8e7148"><span class="cl-8e8797d8">91,052.1</span></p></td><td class="cl-8e8e8ac1"><p class="cl-8e8e7148"><span class="cl-8e8797d8">89,184.5</span></p></td><td class="cl-8e8e8ac1"><p class="cl-8e8e7148"><span class="cl-8e8797d8">37,913.3</span></p></td><td class="cl-8e8e8ac1"><p class="cl-8e8e7148"><span class="cl-8e8797d8">50,444.0</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-8e8e8ac2"><p class="cl-8e8e7148"><span class="cl-8e8797d8">San Jose</span></p></td><td class="cl-8e8e8ac2"><p class="cl-8e8e7148"><span class="cl-8e8797d8">91,805.1</span></p></td><td class="cl-8e8e8ac2"><p class="cl-8e8e7148"><span class="cl-8e8797d8">88,299.0</span></p></td><td class="cl-8e8e8ac2"><p class="cl-8e8e7148"><span class="cl-8e8797d8">34,649.9</span></p></td><td class="cl-8e8e8ac2"><p class="cl-8e8e7148"><span class="cl-8e8797d8">48,412.2</span></p></td></tr></tbody></table></div>
<p><br />
</p>
<p>There are a slew of options for formatting your table, including
adding footnotes, borders, shade and other features. Check out this <a
href="https://epirhandbook.com/en/tables-for-presentation.html">useful</a>
tutorial for an explanation of some of these features.</p>
<p>Once you’re done formatting your table, you can then export it to
Word, PowerPoint or HTML or as an image (PNG) files. To do this, use one
of the following functions: <code>save_as_docx()</code>,
<code>save_as_pptx()</code>, <code>save_as_image()</code>, and
<code>save_as_html()</code>. For the final project, you will likely be
saving your tables as images. Before saving, make sure your working
diirectory is set to the appropriate folder. Then use the
<code>save_as_image()</code> function</p>
<pre class="r"><code>save_as_image(my_table, path = &quot;ncal_income.png&quot;)</code></pre>
<p>You first put in the table <em>my_table</em>, and set the file name
with the png extension. Check your working directory (type in
<code>getwd()</code>). You should see the file <em>ncal_income.png</em>
in the folder.</p>
<div style="margin-bottom:25px;">

</div>
</div>
</div>
<div id="summarizing-variables-using-graphs" class="section level2">
<h2><strong>Summarizing variables using graphs</strong></h2>
<p><br />
</p>
<p>Another way of summarizing variables and their relationships is
through graphs and charts. The main package for R graphing is
<strong>ggplot2</strong> which is a part of the
<strong>tidyverse</strong> package. The graphing function is
<code>ggplot()</code> and it takes on the basic template</p>
<p><br></p>
<pre><code>ggplot(data = &lt;DATA&gt;) +
      &lt;GEOM_FUNCTION&gt;(mapping = aes(x, y)) +
      &lt;OPTIONS&gt;()</code></pre>
<p><br></p>
<ol style="list-style-type: decimal">
<li><p><code>ggplot()</code> is the base function where you specify your
dataset using the <code>data = &lt;DATA&gt;</code> argument.</p></li>
<li><p>You then need to build on this base by using the plus operator
<code>+</code> and <code>&lt;GEOM_FUNCTION&gt;()</code> where
<code>&lt;GEOM_FUNCTION&gt;()</code> is a unique <code>geom</code>
function indicating the type of graph you want to plot. Each unique
function has its unique set of mapping arguments which you specify using
the <code>mapping = aes()</code> argument. Charts and graphs have an
x-axis, y-axis, or both. Check <a
href="https://posit.co/wp-content/uploads/2022/10/data-visualization-1.pdf">this</a>
ggplot cheat sheet for all possible geoms.</p></li>
<li><p><code>&lt;OPTIONS&gt;()</code> are a set of functions you can
specify to change the look of the graph, for example relabelling the
axes or adding a title.</p></li>
</ol>
<p>The basic idea is that a ggplot graphic layers geometric objects
(circles, lines, etc), themes, and scales on top of data.</p>
<p>You first start out with the base layer. It represents the empty
<strong>ggplot</strong> layer defined by the <code>ggplot()</code>
function with the data object whose variable(s) you want to graph.</p>
<pre class="r"><code>ggplot(ncal.tracts)</code></pre>
<p><img
src="lab4_files/figure-html/unnamed-chunk-27-1.png" /><!-- --></p>
<p>We get an empty plot. We haven’t told <code>ggplot()</code> what type
of geometric object(s) we want to plot, nor how the variables should be
mapped to the geometric objects, so we just have a blank plot. We need
<code>geoms</code> to paint the blank canvas.</p>
<p>From here, we add a <code>geom</code> layer to the
<strong>ggplot</strong> object. Layers are added to
<strong>ggplot</strong> objects using <code>+</code>, instead of
<code>%&gt;%</code>, since you are not explicitly piping an object into
each subsequent layer, but adding layers on top of one another. Each
<code>geom</code> is associated with a specific type of graph. For
example, below is code that creates a histogram</p>
<pre class="r"><code>ggplot(ncal.tracts) + 
  geom_histogram(mapping = aes(x=medincome))</code></pre>
<p><img
src="lab4_files/figure-html/unnamed-chunk-28-1.png" /><!-- --></p>
<p><em>ncal.tracts</em> is <code>&lt;DATA&gt;</code>,
<code>geom_histogram()</code> is the
<code>&lt;GEOM_FUNCTION&gt;()</code>, and <code>x=medincome</code> is
the variable in <em>ncal.tracts</em> we are graphing. There is no
<em>y</em> argument specified because a histogram only plots one
variable. Let’s go through how to create the graphs outlined in Handout
4.</p>
<div style="margin-bottom:25px;">

</div>
<div id="bar-charts" class="section level3">
<h3><strong>Bar charts</strong></h3>
<p><br />
</p>
<p>Recall from Handout 4 that we use bar charts to summarize categorical
variables. Bar charts, also known as bar plots, show either the number
or frequency of each category. To create a bar chart, use
<code>geom_bar()</code> for <code>&lt;GEOM_FUNCTION&gt;()</code>. Let’s
show a bar chart of <em>oppzone</em>. We can borrow from the code we
used earlier to create our <em>oppzone</em> frequency table and pipe
this table directly into <code>ggplot()</code>.</p>
<pre class="r"><code>ncal.tracts %&gt;% 
  group_by(oppzone) %&gt;%
  summarize (n = n()) %&gt;%
    mutate(total = sum(n),
        freq = n / total)  %&gt;%
  ggplot() +
    geom_bar(mapping=aes(x=oppzone, y=freq),stat=&quot;identity&quot;) </code></pre>
<p><img
src="lab4_files/figure-html/unnamed-chunk-29-1.png" /><!-- --></p>
<p>We didn’t need to specify <code>data = &lt;DATA&gt;</code> in
<code>ggplot()</code> because it was piped in. Within
<code>aes()</code>, we specified the categorical variable
<em>oppzone</em> on the x-axis and then the proportion of neighborhoods
<em>freq</em> on the y-axis. The argument <code>stat = "identity"</code>
tells <code>ggplot()</code> to plot the exact value listed for the
variable <em>freq</em>.</p>
<p>The X and Y axes labels are not so great. Interpretable labels are
important for getting your message across clearly. We can relabel the
axes using the <code>xlab()</code> and <code>ylab()</code> functions,
which are examples of <code>&lt;OPTIONS&gt;()</code> functions.</p>
<pre class="r"><code>ncal.tracts %&gt;% 
  group_by(oppzone) %&gt;%
  summarize (n = n()) %&gt;%
    mutate(total = sum(n),
        freq = n / total) %&gt;%
  ggplot() +
    geom_bar(mapping=aes(x=oppzone, y=freq),stat=&quot;identity&quot;) +
    xlab(&quot;Opportunity Zone&quot;) +
    ylab(&quot;Proportion&quot;)</code></pre>
<p><img
src="lab4_files/figure-html/unnamed-chunk-30-1.png" /><!-- --></p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="histograms" class="section level3">
<h3><strong>Histograms</strong></h3>
<p><br />
</p>
<p>Histograms are used to summarize a single numeric variable. To create
a histogram, use <code>geom_histogram()</code> for
<code>&lt;GEOM_FUNCTION()&gt;</code>. Let’s create a histogram of median
household income.</p>
<pre class="r"><code>ggplot(ncal.tracts) + 
  geom_histogram(mapping = aes(x=medincome)) +
  xlab(&quot;Median Household Income&quot;) </code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 8 rows containing non-finite values (`stat_bin()`).</code></pre>
<p><img
src="lab4_files/figure-html/unnamed-chunk-31-1.png" /><!-- --></p>
<p>As described earlier, because a single variable is plotted on the
x-axis, we specify <code>x =</code> in <code>aes()</code> but not a
<code>y =</code>. The message before the plot tells us that we can use
the <code>bins =</code> argument to change the number of bins used to
produce the histogram. You can increase the number of bins to make the
bins narrower and thus get a finer grain of detail. Or you can decrease
the number of bins to get a broader visual summary of the shape of the
variable’s distribution. Try changing the number of bins and see what
you get.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="boxplots" class="section level3">
<h3><strong>Boxplots</strong></h3>
<p><br />
</p>
<p>We can use a boxplot to visually summarize the distribution of a
single variable or the relationship between a categorical and numeric
variable. Use <code>geom_boxplot()</code> for
<code>&lt;GEOM_FUNCTION()&gt;</code> to create a boxplot. Let’s examine
median household income.</p>
<pre class="r"><code>ggplot(ncal.tracts) +
     geom_boxplot(mapping = aes(y = medincome))+
    ylab(&quot;Median Household Income&quot;) </code></pre>
<p><img
src="lab4_files/figure-html/unnamed-chunk-32-1.png" /><!-- --></p>
<p>Remember from Handout 4 that the points outside the whiskers
represent outliers. Outliers are defined as having values that are
either larger than the 75th percentile plus 1.5 times the IQR or smaller
than the 25th percentile minus 1.5 times the IQR. The IQR is $55,103,
the 75th percentile is $104,670 and the 25th percentile is $49,568.
While we don’t see outliers at the bottom, we do see outliers at the top
- these are neighborhoods with median income values greater than
$104,670 + 1.5*$55,103 = $187,324.5</p>
<p>Let’s examine the distribution of median income by Opportunity Zone.
Because we are examining the association between two variables, we need
to specify <em>x</em> <strong>and</strong> <em>y</em> variables.</p>
<pre class="r"><code>ggplot(ncal.tracts) +
    geom_boxplot(mapping = aes(x = oppzone, y = medincome)) +
    xlab(&quot;Opportunity Zone&quot;) +
    ylab(&quot;Median Household Income&quot;) </code></pre>
<p><img
src="lab4_files/figure-html/unnamed-chunk-33-1.png" /><!-- --></p>
<p>The boxplot is for all neighborhoods combined. We can use the
<code>facet_wrap()</code>function to separate by city</p>
<pre class="r"><code>ggplot(ncal.tracts) +
  geom_boxplot(mapping = aes(x = oppzone, y = medincome)) +
  xlab(&quot;Opportunity Zone&quot;) +
  ylab(&quot;Median Household Income&quot;) +
  facet_wrap(~city) </code></pre>
<p><img
src="lab4_files/figure-html/unnamed-chunk-34-1.png" /><!-- --></p>
<p>Note the tilde operator <code>~</code> before city.</p>
<p>The labels for <em>oppzone</em> are really long. We can change the
label names (as an exercise, try this on your own) or we can create
horizontal boxplots. To create horizontal boxplots, add the
<code>coord_flip()</code> function at the end.</p>
<pre class="r"><code>ggplot(ncal.tracts) +
    geom_boxplot(mapping = aes(x = oppzone, y = medincome)) +
    facet_wrap(~city) +
    ylab(&quot;Median Household Income&quot;) +
    xlab(&quot;Opportunity Zone&quot;) +
    coord_flip()</code></pre>
<p><img
src="lab4_files/figure-html/unnamed-chunk-35-1.png" /><!-- --></p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="scatterplots" class="section level3">
<h3><strong>Scatterplots</strong></h3>
<p><br />
</p>
<p>The scatterplot is the traditional graph for visualizing the
association between two numeric variables. For scatterplots, we use
<code>geom_point()</code> for <code>&lt;GEOM_FUNCTION&gt;()</code>.
Because we are plotting two variables, we specify an <em>x</em> and
<em>y</em> variable. Does median household income change with greater
percent Hispanic in the neighborhood?</p>
<pre class="r"><code>ggplot(ncal.tracts) +
    geom_point(mapping = aes(x = phisp, y = medincome)) +
    xlab(&quot;Percent Hispanic&quot;) +
    ylab(&quot;Median Household Income&quot;)</code></pre>
<p><img
src="lab4_files/figure-html/unnamed-chunk-36-1.png" /><!-- --></p>
<p>And for each city?</p>
<pre class="r"><code>ggplot(ncal.tracts) +
    geom_point(mapping = aes(x = phisp, y = medincome)) +
    xlab(&quot;Percent Hispanic&quot;) +
    ylab(&quot;Median Household Income&quot;) +
    facet_wrap(~city) </code></pre>
<p><img
src="lab4_files/figure-html/unnamed-chunk-37-1.png" /><!-- --></p>
<p><br></p>
<p>What do these scatter plots suggest about the relationship between
income and percent Hispanic across these four cities?</p>
<p><code>ggplot()</code> is a powerful function, and you can make a lot
of visually captivating graphs. We have just scratched the surface of
its functions and features. The list of all possible plots for
<code>&lt;GEOM_FUNCTION&gt;()</code> can be found <a
href="https://ggplot2.tidyverse.org/reference/">here</a>. You can also
make your graphs really “pretty” and professional looking by altering
graphing features using <code>&lt;OPTIONS()</code>, including colors,
labels, titles and axes. For a list of options that alter various
features of a graph, check out <a
href="http://r4ds.had.co.nz/graphics-for-communication.html">Chapter 28
in RDS</a>.</p>
<p>Here’s your <strong>ggplot2</strong> badge. Wear it with pride!</p>
<center>
<p><img
src="ggplot2.png"
style="width:25.0%" /></p>
</center>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="saving-plots" class="section level3">
<h3><strong>Saving plots</strong></h3>
<p><br />
</p>
<p>You will, on occasion, need to save a plot to a specific file.
Specifically, we expect you to create plots and graphs, save them, and
upload them for your final project. Don’t use the built-in “Export”
button! If you do, your figure is not reproducible – no one will know
how your plot was exported. Instead, use <code>ggsave()</code> by
explicitly creating the figure and exporting</p>
<p>Let’s save the scatterplot of percent Hispanic and median household
income as a .png file named “phisp_inc.png”. First, we save the plot
produced by <code>ggplot()</code> into an R object named
<em>phisp_inc</em></p>
<pre class="r"><code>phisp_inc &lt;- ggplot(ncal.tracts) +
    geom_point(mapping = aes(x = phisp, y = medincome)) +
    xlab(&quot;Percent Hispanic&quot;) +
    ylab(&quot;Median Household Income&quot;)</code></pre>
<p>We then save <em>phisp_inc</em> using <code>ggsave()</code></p>
<pre class="r"><code>ggsave(&quot;phisp_inc.png&quot;, phisp_inc)</code></pre>
<p>Navigate to your working directory folder (type in
<code>getwd()</code> to find what this folder is) and you should see
<em>phisp_inc.png</em>.</p>
<div style="margin-bottom:25px;">

</div>
</div>
</div>
<div id="assignment-4" class="section level2">
<h2><strong>Assignment 4</strong></h2>
<p><br />
</p>
<p>Download and open the <a
href="https://raw.githubusercontent.com/crd150/data/master/yourLastName_firstInitial_asgn04.Rmd">Assignment
4 R Markdown Script</a>. Any response requiring a data analysis task
must be supported by code you generate to produce your result. Just
examining your various objects in the “Environment” section of R Studio
is insufficient—you must use scripted commands. Submit the
<code>Rmd</code> and its knitted <code>html</code> files on Canvas.</p>
<p><br></p>
<ol style="list-style-type: decimal">
<li>As a comprehensive source for neighborhood data, PolicyMap allows
you to examine interesting associations across different dimensions of
neighborhood health and well-being outside of those provided in the U.S.
Census. Let’s examine the potential predictors of resident health in the
City of Sacramento. Bring into R the dataset <a
href="https://raw.githubusercontent.com/crd150/data/master/sac_health_policymap.csv">sac_health_policymap.csv</a>,
which contains census-tract level data on Sacramento downloaded from
PolicyMap. I’ve also uploaded the file on Canvas (Files - Week 4 -
Assignment). Consider the dataset to be cleaned and ready for analysis.
A record layout of the data can be found <a
href="https://raw.githubusercontent.com/crd150/data/master/assgn4_question1_codebook.txt">here</a>.</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><p>Create an appropriate plot that shows the shape of the
distribution for the variable <em>health</em>, which measures the
percent of residents reporting very good to excellent health. Describe
the shape of the distribution. (2 points)</p></li>
<li><p>Examine the association between <em>health</em> and the variable
<em>phys</em>. Based on this examination, briefly describe the
relationship between the variable <em>health</em> and <em>phys</em>. (2
points)</p></li>
<li><p>Create the appropriate plots showing the association between
<em>health</em> and the following variables: <em>foodaccess</em>,
<em>unemp</em>, and <em>medinc</em>. (3 points)</p></li>
<li><p>Based on these plots, briefly describe the relationship between
<em>health</em> and the three variables. Describe any nonlinearities in
the relationships. (2 points)</p></li>
</ol>
<p><br></p>
<ol start="2" style="list-style-type: decimal">
<li>The following questions investigate housing structure in Yolo
County. Bring into R the dataset <a
href="https://raw.githubusercontent.com/crd150/data/master/ca_border_tracts.csv">ca_border_tracts.csv</a>,
which contains 2012-2016 American Community Survey (ACS) data for census
tracts in California and states sharing a boundary with California
(Arizona, Nevada, and Oregon). I’ve also uploaded the file on Canvas
(Files - Week 4 - Assignment). Consider the dataset to be cleaned and
ready for analysis. A record layout of the data can be found <a
href="https://raw.githubusercontent.com/crd150/data/master/assgn4_question2_codebook.txt">here</a>.</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><p>Calculate 90/10 percentile ratios for median household income for
each region (Bay Area, Southern California, Other California, Arizona,
Nevada, and Oregon). Present these values in a presentation-ready table
using <code>flextable()</code>. Which region exhibits the highest
neighborhood income inequality? Lowest? (2 points)</p></li>
<li><p>What is the mean, median, interquartile range, and standard
deviation of the percentage of houses built after 2000 in Yolo County?
Show these values in a presentation-ready table using
<code>flextable()</code>. (2 points)</p></li>
<li><p>What is the correlation between median household income and
percentage of houses built after 2000 in Yolo County? (1 point)</p></li>
<li><p>Show a plot investigating any potential outliers in the
percentage of houses built after 2000 in Yolo County. (2
points)</p></li>
<li><p>Did you find any outliers? If so, how many? What is the mean,
median and standard deviation of the percentage of houses built after
2000 in Yolo County <em>without</em> these outliers? Present these
values in a presentation-ready table using <code>flextable()</code>.
What about the correlation between median household income and
percentage of houses built after 2000? Briefly comment on what you
learned in question 2e. (Hint: How are outliers numerically defined in
the plot in 2d? ) (4 points)</p></li>
</ol>
<hr />
<p><a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This
work is licensed under a
<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative
Commons Attribution-NonCommercial 4.0 International License</a>.</p>
<p>Website created and maintained by <a
href="https://nbrazil.faculty.ucdavis.edu/">Noli Brazil</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>


</body>
</html>
