<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Lab 7a: Segregation</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">CRD 150: Spring 2022</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="syllabus.html">Syllabus</a>
</li>
<li>
  <a href="hw_guidelines.html">Assignment Guidelines</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Labs/Assignments
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="lab1.html">Lab 1</a>
    </li>
    <li>
      <a href="lab2.html">Lab 2</a>
    </li>
    <li>
      <a href="lab3.html">Lab 3</a>
    </li>
    <li>
      <a href="lab4.html">Lab 4</a>
    </li>
    <li>
      <a href="lab5.html">Lab 5</a>
    </li>
    <li>
      <a href="lab6.html">Lab 6</a>
    </li>
    <li>
      <a href="lab7a.html">Lab 7a</a>
    </li>
    <li>
      <a href="lab7b.html">Lab 7b</a>
    </li>
    <li>
      <a href="lab8.html">Lab 8</a>
    </li>
    <li>
      <a href="lab9.html">Lab 9</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Other
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="eligible.html">Eligible Communities</a>
    </li>
    <li>
      <a href="tips.html">R tips</a>
    </li>
    <li>
      <a href="ndata.html">Neighborhood Data Sources</a>
    </li>
    <li>
      <a href="bigopendata.html">Big and Open Data Sources</a>
    </li>
    <li>
      <a href="policymap.html">PolicyMap </a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Lab 7a: Segregation</h1>
<h3 class="subtitle"><h4 style="font-style:normal">
CRD 150 - Quantitative Methods in Community Research
</h4></h3>
<h4 class="author"><h4 style="font-style:normal">
Professor Noli Brazil
</h4></h4>
<h4 class="date"><h4 style="font-style:normal">
May 9, 2022
</h4></h4>

</div>


<style>
p.comment {
background-color: #DBDBDB;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: normal;
}

.figure {
   margin-top: 20px;
   margin-bottom: 20px;
}

h1.title {
  font-weight: bold;
  font-family: Arial;  
}

h2.title {
  font-family: Arial;  
}

</style>
<style type="text/css">
#TOC {
  font-size: 13px;
  font-family: Arial;
}
</style>
<p><br />
</p>
<p>Measures of segregation and other indices of place-based inequality have been fundamental to documenting and understanding the causes and consequences of residential patterns of racial separation. In this guide you will learn how to calculate neighborhood segregation and using R. The objectives of the guide are as follows</p>
<ol style="list-style-type: decimal">
<li>Calculate the Dissimilarity index, a measure of residential evenness.</li>
<li>Calculate the Interaction index, a measure of residential exposure.</li>
</ol>
<p>To accomplish these objectives, you will be working with Census tract data for four of the largest cities in California: Fresno, San Diego, San Jose, and San Francisco.</p>
<p>This lab guide follows closely and supplements the material presented in class Handout 7. <strong>Assignment 7 will be posted at the end of Lab 7b, which will be released Wednesday.</strong></p>
<div style="margin-bottom:25px;">

</div>
<div id="open-up-a-r-markdown-file" class="section level2">
<h2><strong>Open up a R Markdown file</strong></h2>
<p><br />
</p>
<p>Download the <a href="https://raw.githubusercontent.com/crd150/data/master/labtemplate.Rmd">Lab template</a> into an appropriate folder on your hard drive (preferably, a folder named ‘Lab 7a’), open it in R Studio, and type and run your code there. The template is also located on Canvas under Files. The template is also located on Canvas under Files. Change the title (“Lab 7a”) and insert your name and date. Don’t change anything else inside the YAML (the stuff at the top in between the <code>---</code>). Also keep the grey chunk after the YAML. For a rundown on the use of R Markdown, see the <a href="https://crd150.github.io/hw_guidelines.html">assignment guidelines</a>.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="installing-and-loading-packages" class="section level2">
<h2><strong>Installing and loading packages</strong></h2>
<p><br />
</p>
<p>We will not be using any new packages in this lab. You’ll need to load the following packages. Unlike installing, you will always need to load packages whenever you start a new R session. As such, you’ll always need to use <code>library()</code> in your R Markdown file.</p>
<pre class="r"><code>library(sf)
library(tidyverse)
library(tidycensus)
library(tigris)
library(tmap)
library(rmapshaper)
library(knitr)</code></pre>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="read-in-the-data" class="section level2">
<h2><strong>Read in the data</strong></h2>
<p><br />
</p>
<p>The following code uses the Census API to bring in demographic and socioeconomic tract-level data for four of the most populated cities in California: San Diego, San Jose, San Francisco, and Fresno. We won’t go through each line of code in detail because we’ve covered all of these operations and functions in prior labs. We’ve embedded comments within the code that briefly explains what each chunk is doing. Go back to prior guides (or RDS/GWR) if you need further help.</p>
<pre class="r"><code># Bring in 2015-2019 census tract data using the Census API 
ca.tracts19 &lt;- get_acs(geography = &quot;tract&quot;, 
              year = 2019,
              variables = c(tpop = &quot;B03002_001&quot;, 
                            nhwhite = &quot;B03002_003&quot;, nhblk = &quot;B03002_004&quot;,
                            nhasn = &quot;B03002_006&quot;, hisp = &quot;B03002_012&quot;),
              state = &quot;CA&quot;,
              survey = &quot;acs5&quot;,
              output = &quot;wide&quot;,
              geometry = TRUE)

# Make the data tidy, calculate and keep essential vars. 
ca.tracts19 &lt;- ca.tracts19 %&gt;% 
  rename_with(~ sub(&quot;E$&quot;, &quot;&quot;, .x), everything()) %&gt;%
  mutate(pnhwhite19 = 100*(nhwhite/tpop), pnhasn19 = 100*(nhasn/tpop), 
        pnhblk19 = 100*(nhblk/tpop), phisp19 = 100*(hisp/tpop)) %&gt;%
  select(c(GEOID,tpop, pnhwhite19, pnhasn19, pnhblk19, phisp19,
           nhwhite, nhasn, nhblk, hisp))  

# Bring in city boundaries
pl &lt;- places(state = &quot;CA&quot;, year = 2019, cb = TRUE)

# Keep four large cities in CA
large.cities &lt;- filter(pl, NAME == &quot;San Diego&quot; |
                         NAME == &quot;San Jose&quot; | NAME == &quot;San Francisco&quot; |
                         NAME == &quot;Fresno&quot;)

#Keep tracts in large cities 
large.tracts &lt;- ms_clip(target = ca.tracts19, clip = large.cities, remove_slivers = TRUE)</code></pre>
<pre><code>## Rows: 840
## Columns: 11
## $ GEOID      &lt;chr&gt; &quot;06075020900&quot;, &quot;06075021000&quot;, &quot;06085512042&quot;, &quot;06085503306&quot;,…
## $ tpop       &lt;dbl&gt; 4597, 4523, 3020, 4373, 5271, 3726, 3344, 2659, 4750, 3046,…
## $ pnhwhite19 &lt;dbl&gt; 42.136176, 59.142162, 9.105960, 2.721244, 53.101878, 61.782…
## $ pnhasn19   &lt;dbl&gt; 13.182510, 11.983197, 40.596027, 35.307569, 36.084235, 2.44…
## $ pnhblk19   &lt;dbl&gt; 2.4146182, 2.0561574, 4.1059603, 1.1433798, 0.2466325, 1.28…
## $ phisp19    &lt;dbl&gt; 39.090711, 19.102366, 37.549669, 59.547222, 5.919180, 31.96…
## $ nhwhite    &lt;dbl&gt; 1937, 2675, 275, 119, 2799, 2302, 2220, 2211, 911, 413, 204…
## $ nhasn      &lt;dbl&gt; 606, 542, 1226, 1544, 1902, 91, 124, 48, 130, 498, 2851, 22…
## $ nhblk      &lt;dbl&gt; 111, 93, 124, 50, 13, 48, 108, 15, 637, 188, 637, 251, 636,…
## $ hisp       &lt;dbl&gt; 1797, 864, 1134, 2604, 312, 1191, 780, 328, 3035, 1894, 241…
## $ geometry   &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((-122.421 37..., MULTIPOLYGON (…</code></pre>
<p>The object <em>large.tracts</em> contains the census tracts located in the four cities. When you view the dataset, you’ll notice that we don’t have any variable indicating which city each tract belongs to. We need the city identifier to calculate segregation for each city. Let’s append the city GEOID and NAME from the object <em>large.cities</em> to each tract in the object <em>large.tracts</em>. We do this by using the <code>st_join()</code> function, which is a part of the <strong>sf</strong> package. The function will join the variables from <em>large.cities</em> to <em>large.tracts</em> based on geographic location. That is, if a tract is located within a city, that city’s values from <em>large.cities</em> will be appended to that tract.</p>
<p>First, look at the variables already in <em>large.tracts</em>.</p>
<pre class="r"><code>names(large.tracts)</code></pre>
<pre><code>##  [1] &quot;GEOID&quot;      &quot;tpop&quot;       &quot;pnhwhite19&quot; &quot;pnhasn19&quot;   &quot;pnhblk19&quot;  
##  [6] &quot;phisp19&quot;    &quot;nhwhite&quot;    &quot;nhasn&quot;      &quot;nhblk&quot;      &quot;hisp&quot;      
## [11] &quot;geometry&quot;</code></pre>
<p>Then <code>st_join()</code></p>
<pre class="r"><code>large.tracts &lt;- large.tracts %&gt;%
                st_join(large.cities)</code></pre>
<p>This function joins the variables from <em>large.cities</em> to the data frame <em>large.tracts</em>, including the variables <em>GEOID.y</em> and <em>NAME</em>, which represent the city GEOID and name.</p>
<pre class="r"><code>names(large.tracts)</code></pre>
<pre><code>##  [1] &quot;GEOID.x&quot;    &quot;tpop&quot;       &quot;pnhwhite19&quot; &quot;pnhasn19&quot;   &quot;pnhblk19&quot;  
##  [6] &quot;phisp19&quot;    &quot;nhwhite&quot;    &quot;nhasn&quot;      &quot;nhblk&quot;      &quot;hisp&quot;      
## [11] &quot;STATEFP&quot;    &quot;PLACEFP&quot;    &quot;PLACENS&quot;    &quot;AFFGEOID&quot;   &quot;GEOID.y&quot;   
## [16] &quot;NAME&quot;       &quot;LSAD&quot;       &quot;ALAND&quot;      &quot;AWATER&quot;     &quot;geometry&quot;</code></pre>
<p>We don’t need all of these new variables, so let’s use <code>select()</code> to remove the variables we don’t need.</p>
<pre class="r"><code>large.tracts &lt;- large.tracts %&gt;%
                select(-(STATEFP:AFFGEOID), -(LSAD:AWATER))</code></pre>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="mapping" class="section level2">
<h2><strong>Mapping</strong></h2>
<p><br />
</p>
<p>Before calculating segregation, you should map neighborhood racial/ethnic composition in order to gain a visual understanding of how race/ethnic groups are spatially distributed in your study region. For example, let’s map percent Hispanic in Fresno.</p>
<pre class="r"><code>large.tracts %&gt;%
  filter(NAME == &quot;Fresno&quot;) %&gt;%
  tm_shape(unit = &quot;mi&quot;) +
    tm_polygons(col = &quot;phisp19&quot;, style = &quot;quantile&quot;,palette = &quot;Reds&quot;, 
              border.alpha = 0, title = &quot;&quot;) +
    tm_scale_bar(breaks = c(0, 1, 2), text.size = 0.75, position = c(&quot;right&quot;, &quot;bottom&quot;)) + tm_layout(main.title = &quot;Percent Hispanic in Fresno City Tracts&quot;, main.title.size = 0.9, frame = FALSE)</code></pre>
<p><img src="lab7a_files/figure-html/unnamed-chunk-8-1.png" /><!-- --></p>
<p>How does this spatial distribution compare to percent non-Hispanic white?</p>
<pre class="r"><code>large.tracts %&gt;%
  filter(NAME == &quot;Fresno&quot;) %&gt;%
tm_shape(unit = &quot;mi&quot;) +
  tm_polygons(col = &quot;pnhwhite19&quot;, style = &quot;quantile&quot;,palette = &quot;Reds&quot;, 
              border.alpha = 0, title = &quot;&quot;) +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = 0.75, position = c(&quot;right&quot;, &quot;bottom&quot;)) +  tm_layout(main.title = &quot;Percent White in Fresno City Tracts&quot;, main.title.size = 0.9,
            frame = FALSE)</code></pre>
<p><img src="lab7a_files/figure-html/unnamed-chunk-9-1.png" /><!-- --></p>
<p>It looks like a North/South divide. Map the other two race/ethnic groups in Fresno and all the groups in the other three cities.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="dissimilarity-index" class="section level2">
<h2><strong>Dissimilarity Index</strong></h2>
<p><br />
</p>
<p>The most common measure of residential evenness is the Dissimilarity Index <em>D</em>. To calculate <em>D</em>, we’ll follow the Dissimilarity index formula on page 3 of Handout 7. We will calculate Black/White, Hispanic/White, and Asian/White Dissimilarity. We first need to calculate the total population by race/ethnicity for each city. This is the value <span class="math inline">\(T_m\)</span> and <span class="math inline">\(T_k\)</span> in the formula. We do this by using the <code>group_by()</code> and <code>mutate()</code> functions.</p>
<pre class="r"><code>large.tracts &lt;- large.tracts %&gt;%
      group_by(NAME) %&gt;%
      mutate(nhwhitec = sum(nhwhite), nhasnc = sum(nhasn), 
             nhblkc = sum(nhblk), hispc = sum(hisp), 
             tpopc = sum(tpop)) %&gt;%
      ungroup()</code></pre>
<p>We already covered <code>group_by()</code> in <a href="https://crd150.github.io/lab4.html">Lab 4</a>, but as a reminder, the <code>group_by()</code> function tells R that all future functions on <em>large.tracts</em> will be grouped according to the variable <em>NAME</em>, which is the city name. We use the <code>sum()</code> function within the <code>mutate()</code> function to sum up, for example, the non-Hispanic white population <em>nhwhite</em> for each city. We name this variable <em>nhwhitec</em>. If you type in <code>View(large.tracts)</code>, you should find that the variable <em>nhwhitec</em> provides the same value for all tracts within the same city. We do this for all the other race/ethnic groups.</p>
<p>The function <code>ungroup()</code> at the end of the code tells R to stop the grouping. For example, we see the results after grouping by <em>NAME</em></p>
<pre class="r"><code>large.tracts %&gt;%
    group_by(NAME)</code></pre>
<pre><code>## Simple feature collection with 840 features and 17 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -123.0139 ymin: 32.53471 xmax: -116.9057 ymax: 37.86334
## Geodetic CRS:  NAD83
## # A tibble: 840 × 18
## # Groups:   NAME [4]
##    GEOID.x   tpop pnhwhite19 pnhasn19 pnhblk19 phisp19 nhwhite nhasn nhblk  hisp
##    &lt;chr&gt;    &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 0607502…  4597      42.1     13.2     2.41    39.1     1937   606   111  1797
##  2 0607502…  4523      59.1     12.0     2.06    19.1     2675   542    93   864
##  3 0608551…  3020       9.11    40.6     4.11    37.5      275  1226   124  1134
##  4 0608550…  4373       2.72    35.3     1.14    59.5      119  1544    50  2604
##  5 0607300…  5271      53.1     36.1     0.247    5.92    2799  1902    13   312
##  6 0607300…  3726      61.8      2.44    1.29    32.0     2302    91    48  1191
##  7 0607300…  3344      66.4      3.71    3.23    23.3     2220   124   108   780
##  8 0607300…  2659      83.2      1.81    0.564   12.3     2211    48    15   328
##  9 0601900…  4750      19.2      2.74   13.4     63.9      911   130   637  3035
## 10 0601900…  3046      13.6     16.3     6.17    62.2      413   498   188  1894
## # … with 830 more rows, and 8 more variables: GEOID.y &lt;chr&gt;, NAME &lt;chr&gt;,
## #   geometry &lt;MULTIPOLYGON [°]&gt;, nhwhitec &lt;dbl&gt;, nhasnc &lt;dbl&gt;, nhblkc &lt;dbl&gt;,
## #   hispc &lt;dbl&gt;, tpopc &lt;dbl&gt;</code></pre>
<p>that the tibble <em>large.tracts</em> is grouped (<em>Groups: NAME [4]</em>). Use <code>ungroup()</code> to, well, ungroup the tibble.</p>
<pre class="r"><code>large.tracts %&gt;%
    group_by(NAME) %&gt;%
    ungroup()</code></pre>
<pre><code>## Simple feature collection with 840 features and 17 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -123.0139 ymin: 32.53471 xmax: -116.9057 ymax: 37.86334
## Geodetic CRS:  NAD83
## # A tibble: 840 × 18
##    GEOID.x   tpop pnhwhite19 pnhasn19 pnhblk19 phisp19 nhwhite nhasn nhblk  hisp
##    &lt;chr&gt;    &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 0607502…  4597      42.1     13.2     2.41    39.1     1937   606   111  1797
##  2 0607502…  4523      59.1     12.0     2.06    19.1     2675   542    93   864
##  3 0608551…  3020       9.11    40.6     4.11    37.5      275  1226   124  1134
##  4 0608550…  4373       2.72    35.3     1.14    59.5      119  1544    50  2604
##  5 0607300…  5271      53.1     36.1     0.247    5.92    2799  1902    13   312
##  6 0607300…  3726      61.8      2.44    1.29    32.0     2302    91    48  1191
##  7 0607300…  3344      66.4      3.71    3.23    23.3     2220   124   108   780
##  8 0607300…  2659      83.2      1.81    0.564   12.3     2211    48    15   328
##  9 0601900…  4750      19.2      2.74   13.4     63.9      911   130   637  3035
## 10 0601900…  3046      13.6     16.3     6.17    62.2      413   498   188  1894
## # … with 830 more rows, and 8 more variables: GEOID.y &lt;chr&gt;, NAME &lt;chr&gt;,
## #   geometry &lt;MULTIPOLYGON [°]&gt;, nhwhitec &lt;dbl&gt;, nhasnc &lt;dbl&gt;, nhblkc &lt;dbl&gt;,
## #   hispc &lt;dbl&gt;, tpopc &lt;dbl&gt;</code></pre>
<p>and the grouping is gone! It’s always good practice to <code>ungroup()</code> a data set if you are saving it for future use (rather than using it as a summary table as we’ve doing so far in the class).</p>
<p>We’ve got the values for <span class="math inline">\(T_m\)</span>, <span class="math inline">\(T_k\)</span>, <span class="math inline">\(t_{im}\)</span>, and <span class="math inline">\(t_{ik}\)</span>, so we can calculate the rest of the formula, breaking it down piece-by-piece like we did in the handout and in lecture. The following code calculates the Dissimilarity indices.</p>
<pre class="r"><code>large.tracts %&gt;%
      group_by(NAME) %&gt;%
      mutate(d.wb = abs(nhblk/nhblkc-nhwhite/nhwhitec),
              d.wa = abs(nhasn/nhasnc-nhwhite/nhwhitec), 
              d.wh = abs(hisp/hispc-nhwhite/nhwhitec)) %&gt;%
      summarize(BWD = 0.5*sum(d.wb, na.rm=TRUE), AWD = 0.5*sum(d.wa, na.rm=TRUE),
                HWD = 0.5*sum(d.wh, na.rm=TRUE)) %&gt;%
      ungroup()</code></pre>
<pre><code>## Simple feature collection with 4 features and 4 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -123.0139 ymin: 32.53471 xmax: -116.9057 ymax: 37.86334
## Geodetic CRS:  NAD83
## # A tibble: 4 × 5
##   NAME            BWD   AWD   HWD                                       geometry
##   &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;                             &lt;MULTIPOLYGON [°]&gt;
## 1 Fresno        0.466 0.389 0.406 (((-119.6798 36.7574, -119.6731 36.75744, -11…
## 2 San Diego     0.557 0.469 0.536 (((-117.2526 32.75295, -117.253 32.75186, -11…
## 3 San Francisco 0.526 0.399 0.431 (((-123.0128 37.6965, -123.0075 37.69593, -12…
## 4 San Jose      0.420 0.479 0.487 (((-121.7575 37.39844, -121.7585 37.3954, -12…</code></pre>
<p><br></p>
<p>Let’s break the code down so we’re all on the same page. We use <code>mutate()</code> to calculate the tract level contributions to the index, i.e. the value <span class="math inline">\(\left|\frac{t_{rm}}{T_m} - \frac{t_{rk}}{T_k}\right|\)</span> for each neighborhood <span class="math inline">\(i\)</span>. Next, we turn to <code>summarize()</code> to finish the rest of the job. Within <code>summarize()</code>, we use the function <code>sum()</code> to add the neighborhood specific values in Equation 1 in Handout 7. In other words, <code>sum()</code> is performing the <span class="math inline">\(\sum\limits_{i}^{N}\)</span> that adds up <span class="math inline">\(\left|\frac{t_{rm}}{T_m} - \frac{t_{rk}}{T_k}\right|\)</span>. Finally, multiply the summed up value by 0.5 to get the final indices.</p>
<p><br></p>
<p>The resulting values provide the Dissimilarity indices for Black/White (<em>BWD</em>), Asian/White (<em>AWD</em>), and Hispanic/White (<em>HWD</em>). In all of these cases, we calculate segregation from white residents, but you can calculate segregation for any race/ethnicity combination (e.g. Black/Hispanic). Instead of just copying and pasting the chunk of code above into your console, make sure you understand what each line of code is doing. Not only will it help you become a more seasoned R coder, but it will also help you better understand the underlying math behind the Dissimilarity index.</p>
<p><br></p>
<p>The results table we got above is a little messy. Let’s clean it up by doing two things: (1) Drop the geometry column using <code>st_drop_geometry()</code>, which is a part of the <strong>sf</strong> package, and (2) use the <code>kable()</code> function, which is a part of the <strong>knitr</strong> package, to make a nicely formatted table. The <code>st_drop_geometry()</code> function removes the <em>geometry</em> variable, and thus makes the object <em>large.tracts</em> no longer spatial. We add these functions to the bottom of the code we ran directly above.</p>
<pre class="r"><code>large.tracts %&gt;%
      group_by(NAME) %&gt;%
      mutate(d.wb = abs(nhblk/nhblkc-nhwhite/nhwhitec),
              d.wa = abs(nhasn/nhasnc-nhwhite/nhwhitec), 
              d.wh = abs(hisp/hispc-nhwhite/nhwhitec)) %&gt;%
      summarize(BWD = 0.5*sum(d.wb, na.rm=TRUE), AWD = 0.5*sum(d.wa, na.rm=TRUE),
                HWD = 0.5*sum(d.wh, na.rm=TRUE)) %&gt;%
      ungroup() %&gt;%
      st_drop_geometry() %&gt;%
      kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">NAME</th>
<th align="right">BWD</th>
<th align="right">AWD</th>
<th align="right">HWD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Fresno</td>
<td align="right">0.466</td>
<td align="right">0.389</td>
<td align="right">0.406</td>
</tr>
<tr class="even">
<td align="left">San Diego</td>
<td align="right">0.557</td>
<td align="right">0.469</td>
<td align="right">0.536</td>
</tr>
<tr class="odd">
<td align="left">San Francisco</td>
<td align="right">0.526</td>
<td align="right">0.399</td>
<td align="right">0.431</td>
</tr>
<tr class="even">
<td align="left">San Jose</td>
<td align="right">0.420</td>
<td align="right">0.479</td>
<td align="right">0.487</td>
</tr>
</tbody>
</table>
<p>Looks much better. The argument <code>digits = 3</code> within <code>kable()</code> rounds up values to three significant digits after the decimal.</p>
<p>The Dissimilarity index for Black/White in Fresno is 0.466. The interpretation of this value is that 46.6% of black residents would need to move neighborhoods in order to achieve a uniform distribution of black and white residents across neighborhoods in the city.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="interaction-index" class="section level2">
<h2><strong>Interaction Index</strong></h2>
<p><br />
</p>
<p>The most common measure of exposure is the Interaction Index <span class="math inline">\(P^*\)</span>. Let’s calculate the exposure of black (<em>BWI</em>), Asian (<em>AWI</em>), Hispanic (<em>HWI</em>) residents to white residents using the formula on page 6 of Handout 7. We present the results in a nice table using the function <code>kable()</code>.</p>
<pre class="r"><code>large.tracts %&gt;%
      group_by(NAME) %&gt;%
      mutate(i.wb = (nhblk/nhblkc)*(nhwhite/tpop),
              i.wa = (nhasn/nhasnc)*(nhwhite/tpop), 
              i.wh = (hisp/hispc)*(nhwhite/tpop)) %&gt;%
      summarize(BWI = sum(i.wb, na.rm=TRUE), AWI = sum(i.wa, na.rm=TRUE),
                HWI = sum(i.wh, na.rm=TRUE)) %&gt;%
      ungroup() %&gt;%
      st_drop_geometry() %&gt;%
      kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">NAME</th>
<th align="right">BWI</th>
<th align="right">AWI</th>
<th align="right">HWI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Fresno</td>
<td align="right">0.226</td>
<td align="right">0.265</td>
<td align="right">0.223</td>
</tr>
<tr class="even">
<td align="left">San Diego</td>
<td align="right">0.302</td>
<td align="right">0.381</td>
<td align="right">0.279</td>
</tr>
<tr class="odd">
<td align="left">San Francisco</td>
<td align="right">0.298</td>
<td align="right">0.326</td>
<td align="right">0.338</td>
</tr>
<tr class="even">
<td align="left">San Jose</td>
<td align="right">0.284</td>
<td align="right">0.219</td>
<td align="right">0.208</td>
</tr>
</tbody>
</table>
<p>The <code>mutate()</code> function is creating the tract specific values <span class="math inline">\(\frac{t_{im}}{T_m} * \frac{t_{ik}}{t_i}\)</span>. We then turn to <code>summarize()</code> to perform the <span class="math inline">\(\sum\limits_{i}^{N}\)</span>.</p>
<p>The probability of a Black resident “interacting” with a white person in his or her neighborhood is about 22.6% in Fresno. We can also interpret this to mean that 23 of every 100 people a Black person meets in his or her neighborhood will be white. Remember that interaction is not symmetric. Calculate the interaction of white residents with Black residents in the other cities and see if there are major differences with the values we calculated above.</p>
<hr />
<p><a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.</p>
<p>Website created and maintained by <a href="https://nbrazil.faculty.ucdavis.edu/">Noli Brazil</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "site_libs/mathjax-local/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
