<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Lab 8: Segregation and Gentrification</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="site_libs/anchor-sections-1.0/anchor-sections.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">CRD 150: Winter 2021</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="syllabus.html">Syllabus</a>
</li>
<li>
  <a href="hw_guidelines.html">Assignment Guidelines</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Labs/Assignments
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="lab1.html">Lab 1</a>
    </li>
    <li>
      <a href="lab2.html">Lab 2</a>
    </li>
    <li>
      <a href="lab3.html">Lab 3</a>
    </li>
    <li>
      <a href="lab4.html">Lab 4</a>
    </li>
    <li>
      <a href="lab5.html">Lab 5</a>
    </li>
    <li>
      <a href="lab6.html">Lab 6</a>
    </li>
    <li>
      <a href="lab7.html">Lab 7</a>
    </li>
    <li>
      <a href="lab8.html">Lab 8</a>
    </li>
    <li>
      <a href="lab9.html">Lab 9</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Other
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="eligible.html">Eligible Communities</a>
    </li>
    <li>
      <a href="tips.html">R tips</a>
    </li>
    <li>
      <a href="ndata.html">Neighborhood Data Sources</a>
    </li>
    <li>
      <a href="bigopendata.html">Big and Open Data Sources</a>
    </li>
    <li>
      <a href="policymap.html">PolicyMap</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Lab 8: Segregation and Gentrification</h1>
<h3 class="subtitle"><h4 style="font-style:normal">
CRD 150 - Quantitative Methods in Community Research
</h4></h3>
<h4 class="author"><h4 style="font-style:normal">
Professor Noli Brazil
</h4></h4>
<h4 class="date"><h4 style="font-style:normal">
February 25, 2021
</h4></h4>

</div>


<style>
p.comment {
background-color: #DBDBDB;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: normal;
}

.figure {
   margin-top: 20px;
   margin-bottom: 20px;
}

h1.title {
  font-weight: bold;
  font-family: Arial;  
}

h2.title {
  font-family: Arial;  
}

</style>
<style type="text/css">
#TOC {
  font-size: 13px;
  font-family: Arial;
}
</style>
<p><br />
</p>
<p>In this guide you will learn how to calculate neighborhood segregation and gentrification measures using R. The objectives of the guide are as follows</p>
<ol style="list-style-type: decimal">
<li>Calculate the Dissimilarity index, a measure of residential evenness.</li>
<li>Calculate the measure of gentrification used by Ding et al. (2016).</li>
</ol>
<p>To accomplish these objectives, you will be working with Census tract data for four of the largest cities in California: Fresno, San Diego, San Jose, and San Francisco.</p>
<p>This lab guide follows closely and supplements the material presented in class Handout 8.</p>
<p class="comment">
<strong>Assignment 8 is due by 12:00 pm, March 4th on Canvas.</strong> See <a href="https://crd150.github.io/hw_guidelines.html">here</a> for assignment guidelines. You must submit an <code>.Rmd</code> file and its associated <code>.html</code> file. Name the files: yourLastName_firstInitial_asgn08. For example: brazil_n_asgn08.
</p>
<div style="margin-bottom:25px;">

</div>
<div id="open-up-a-r-markdown-file" class="section level2">
<h2><strong>Open up a R Markdown file</strong></h2>
<p><br />
</p>
<p>Download the <a href="https://raw.githubusercontent.com/crd150/data/master/labtemplate.Rmd">Lab template</a> into an appropriate folder on your hard drive (preferably, a folder named ‘Lab 8’), open it in R Studio, and type and run your code there. The template is also located on Canvas under Files. The template is also located on Canvas under Files. Change the title (“Lab 8”) and insert your name and date. Don’t change anything else inside the YAML (the stuff at the top in between the <code>---</code>). Also keep the grey chunk after the YAML. For a rundown on the use of R Markdown, see the <a href="https://crd150.github.io/hw_guidelines.html">assignment guidelines</a>.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="installing-and-loading-packages" class="section level2">
<h2><strong>Installing and loading packages</strong></h2>
<p><br />
</p>
<p>We will not be using any new packages in this lab. You’ll need to load the following packages. Unlike installing, you will always need to load packages whenever you start a new R session. As such, you’ll always need to use <code>library()</code> in your R Markdown file.</p>
<pre class="r"><code>library(sf)
library(tidyverse)
library(tidycensus)
library(tigris)
library(tmap)
library(rmapshaper)
library(knitr)</code></pre>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="segregation" class="section level2">
<h2><strong>Segregation</strong></h2>
<p><br />
</p>
<p>Measures of segregation have been fundamental to documenting and understanding the causes and consequences of residential patterns of racial separation. Let’s calculate one of the most common measures of racial residential segregation: Dissimilarity, which measures residential evenness.</p>
<div style="margin-bottom:25px;">

</div>
<div id="read-in-the-data" class="section level3">
<h3><strong>Read in the data</strong></h3>
<p><br />
</p>
<p>The following code uses the Census API to bring in demographic and socioeconomic tract-level data for four of the most populated cities in California: San Diego, San Jose, San Francisco, and Fresno. We won’t go through each line of code in detail because we’ve covered all of these operations and functions in prior labs. We’ve embedded comments within the code that briefly explains what each chunk is doing. Go back to prior guides (or RDS/GWR) if you need further help. I’ve appended <em>19</em> to the end of each variable name to signify these are 2019 data. This is done to distinguish these variables from the 2010 ACS data, which we’ll be downloading later when we measure gentrification.</p>
<pre class="r"><code># Bring in 2015-2019 census tract data using the Census API 
ca.tracts19 &lt;- get_acs(geography = &quot;tract&quot;, 
              year = 2019,
              variables = c(tpop = &quot;B03002_001&quot;, 
                            nhwhite = &quot;B03002_003&quot;, nhblk = &quot;B03002_004&quot;,
                            nhasn = &quot;B03002_006&quot;, hisp = &quot;B03002_012&quot;,
                            medinc19 = &quot;B19013_001&quot;, rent19  = &quot;B25064_001&quot;,
                            houseval19 = &quot;B25077_001&quot;, bach = &quot;B15003_022&quot;,
                            masters = &quot;B15003_023&quot;, prof = &quot;B15003_024&quot;,
                            phd = &quot;B15003_025&quot;, totcol = &quot;B15003_001&quot;),
              state = &quot;CA&quot;,
              survey = &quot;acs5&quot;,
              output = &quot;wide&quot;,
              geometry = TRUE)

# Make the data tidy, calculate and keep essential vars. 
ca.tracts19 &lt;- ca.tracts19 %&gt;% 
  rename_with(~ sub(&quot;E$&quot;, &quot;&quot;, .x), everything()) %&gt;%
  mutate(pnhwhite19 = 100*(nhwhite/tpop), pnhasn19 = 100*(nhasn/tpop), 
        pnhblk19 = 100*(nhblk/tpop), phisp19 = 100*(hisp/tpop), 
        pcol19 = 100*(bach+masters+prof+phd)/totcol) %&gt;%
  select(c(GEOID,tpop, pnhwhite19, pnhasn19, pnhblk19, phisp19,
           nhwhite, nhasn, nhblk, hisp,
           medinc19, rent19, houseval19, pcol19))  

# Bring in city boundaries
pl &lt;- places(state = &quot;CA&quot;, year = 2019, cb = TRUE)

# Keep four large cities in CA
large.cities &lt;- filter(pl, NAME == &quot;San Diego&quot; |
                         NAME == &quot;San Jose&quot; | NAME == &quot;San Francisco&quot; |
                         NAME == &quot;Fresno&quot;)

#Keep tracts in large cities 
large.tracts &lt;- ms_clip(target = ca.tracts19, clip = large.cities, remove_slivers = TRUE)</code></pre>
<p>The object <em>large.tracts</em> contains the census tracts located in the four cities. When you view the dataset, you’ll notice that we don’t have any variable indicating which city each tract belongs to. We need the city identifier to calculate segregation for each city and to merge in 2010 place or city-level data when we measure gentrification later on. Let’s append the city GEOID and NAME from the object <em>large.cities</em> to each tract in the object <em>large.tracts</em>. We do this by using the <code>st_join()</code> function, which is a part of the <strong>sf</strong> package. First, look at the variables already in <em>large.tracts</em>.</p>
<pre class="r"><code>names(large.tracts)</code></pre>
<pre><code>##  [1] &quot;GEOID&quot;      &quot;tpop&quot;       &quot;pnhwhite19&quot; &quot;pnhasn19&quot;   &quot;pnhblk19&quot;  
##  [6] &quot;phisp19&quot;    &quot;nhwhite&quot;    &quot;nhasn&quot;      &quot;nhblk&quot;      &quot;hisp&quot;      
## [11] &quot;medinc19&quot;   &quot;rent19&quot;     &quot;houseval19&quot; &quot;pcol19&quot;     &quot;geometry&quot;</code></pre>
<p>Then <code>st_join()</code></p>
<pre class="r"><code>large.tracts &lt;- large.tracts %&gt;%
                st_join(large.cities, left=FALSE)</code></pre>
<p>This function joins the variables from <em>large.cities</em> to the data frame <em>large.tracts</em>, including the variables <em>GEOID.y</em> and <em>NAME</em>, which represent the city GEOID and name.</p>
<pre class="r"><code>names(large.tracts)</code></pre>
<pre><code>##  [1] &quot;GEOID.x&quot;    &quot;tpop&quot;       &quot;pnhwhite19&quot; &quot;pnhasn19&quot;   &quot;pnhblk19&quot;  
##  [6] &quot;phisp19&quot;    &quot;nhwhite&quot;    &quot;nhasn&quot;      &quot;nhblk&quot;      &quot;hisp&quot;      
## [11] &quot;medinc19&quot;   &quot;rent19&quot;     &quot;houseval19&quot; &quot;pcol19&quot;     &quot;STATEFP&quot;   
## [16] &quot;PLACEFP&quot;    &quot;PLACENS&quot;    &quot;AFFGEOID&quot;   &quot;GEOID.y&quot;    &quot;NAME&quot;      
## [21] &quot;LSAD&quot;       &quot;ALAND&quot;      &quot;AWATER&quot;     &quot;geometry&quot;</code></pre>
<p>We don’t need all of these variables, so let’s use <code>select()</code> to remove the variables we don’t need.</p>
<pre class="r"><code>large.tracts &lt;- large.tracts %&gt;%
                select(-(STATEFP:AFFGEOID), -(LSAD:AWATER))</code></pre>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="mapping" class="section level3">
<h3><strong>Mapping</strong></h3>
<p><br />
</p>
<p>Before calculating segregation, you should map neighborhood racial/ethnic composition in order to gain a visual understanding of how race/ethnic groups are spatially distributed in your study region. For example, let’s map percent Hispanic in Fresno.</p>
<pre class="r"><code>large.tracts %&gt;%
  filter(NAME == &quot;Fresno&quot;) %&gt;%
  tm_shape(unit = &quot;mi&quot;) +
    tm_polygons(col = &quot;phisp19&quot;, style = &quot;quantile&quot;,palette = &quot;Reds&quot;, 
              border.alpha = 0, title = &quot;&quot;) +
    tm_scale_bar(breaks = c(0, 1, 2), text.size = 0.75, position = c(&quot;right&quot;, &quot;bottom&quot;)) + tm_layout(main.title = &quot;Percent Hispanic in Fresno City Tracts&quot;, main.title.size = 0.9, frame = FALSE)</code></pre>
<p><img src="lab8_files/figure-html/unnamed-chunk-7-1.png" /><!-- --></p>
<p>How does this spatial distribution compare to percent non-Hispanic white?</p>
<pre class="r"><code>large.tracts %&gt;%
  filter(NAME == &quot;Fresno&quot;) %&gt;%
tm_shape(unit = &quot;mi&quot;) +
  tm_polygons(col = &quot;pnhwhite19&quot;, style = &quot;quantile&quot;,palette = &quot;Reds&quot;, 
              border.alpha = 0, title = &quot;&quot;) +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = 0.75, position = c(&quot;right&quot;, &quot;bottom&quot;)) +  tm_layout(main.title = &quot;Percent White in Fresno City Tracts&quot;, main.title.size = 0.9,
            frame = FALSE)</code></pre>
<p><img src="lab8_files/figure-html/unnamed-chunk-8-1.png" /><!-- --></p>
<p>It looks like a North/South divide. Map the other two race/ethnic groups in Fresno and all the groups in the other three cities.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="dissimilarity-index" class="section level3">
<h3><strong>Dissimilarity Index</strong></h3>
<p><br />
</p>
<p>The most common measure of residential evenness is the Dissimilarity Index <em>D</em>. To calculate <em>D</em>, we’ll follow the Dissimilarity index formula on page 8 of Handout 8. We will calculate Black/White, Hispanic/White, and Asian/White Dissimilarity. We first need to calculate the total population by race/ethnicity for each city. This is the value <span class="math inline">\(T_m\)</span> and <span class="math inline">\(T_k\)</span> in the formula. We do this by using the <code>group_by()</code> and <code>mutate()</code> functions.</p>
<pre class="r"><code>large.tracts &lt;- large.tracts %&gt;%
      group_by(NAME) %&gt;%
      mutate(nhwhitec = sum(nhwhite), nhasnc = sum(nhasn), 
             nhblkc = sum(nhblk), hispc = sum(hisp), 
             tpopc = sum(tpop)) %&gt;%
      ungroup()</code></pre>
<p>The <code>group_by()</code> function tells R that all future functions on <em>large.tracts</em> will be grouped according to the variable <em>NAME</em>, which is the city name. We use the <code>sum()</code> function within the <code>mutate()</code> function to sum up, for example, the non-Hispanic white population <em>nhwhite</em> for each city. We name this variable <em>nhwhitec</em>. If you type in <code>View(large.tracts)</code>, you should find that the variable <em>nhwhitec</em> provides the same value for all tracts within the same city. We do this for all the other race/ethnic groups.</p>
<p>The function <code>ungroup()</code> at the end of the code tells R to stop the grouping. For example, we see the results after grouping by <em>NAME</em></p>
<pre class="r"><code>large.tracts %&gt;%
    group_by(NAME)</code></pre>
<pre><code>## Simple feature collection with 825 features and 21 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: -123.0139 ymin: 32.53471 xmax: -116.9057 ymax: 37.86334
## geographic CRS: NAD83
## # A tibble: 825 x 22
## # Groups:   NAME [4]
##    GEOID.x   tpop pnhwhite19 pnhasn19 pnhblk19 phisp19 nhwhite nhasn nhblk  hisp
##    &lt;chr&gt;    &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 0607502…  4597      42.1     13.2     2.41    39.1     1937   606   111  1797
##  2 0607502…  4523      59.1     12.0     2.06    19.1     2675   542    93   864
##  3 0608551…  3020       9.11    40.6     4.11    37.5      275  1226   124  1134
##  4 0608550…  4373       2.72    35.3     1.14    59.5      119  1544    50  2604
##  5 0607300…  5271      53.1     36.1     0.247    5.92    2799  1902    13   312
##  6 0607300…  3726      61.8      2.44    1.29    32.0     2302    91    48  1191
##  7 0607300…  3344      66.4      3.71    3.23    23.3     2220   124   108   780
##  8 0607300…  2659      83.2      1.81    0.564   12.3     2211    48    15   328
##  9 0601900…  4750      19.2      2.74   13.4     63.9      911   130   637  3035
## 10 0601900…  3046      13.6     16.3     6.17    62.2      413   498   188  1894
## # … with 815 more rows, and 12 more variables: medinc19 &lt;dbl&gt;, rent19 &lt;dbl&gt;,
## #   houseval19 &lt;dbl&gt;, pcol19 &lt;dbl&gt;, GEOID.y &lt;chr&gt;, NAME &lt;chr&gt;,
## #   geometry &lt;MULTIPOLYGON [°]&gt;, nhwhitec &lt;dbl&gt;, nhasnc &lt;dbl&gt;, nhblkc &lt;dbl&gt;,
## #   hispc &lt;dbl&gt;, tpopc &lt;dbl&gt;</code></pre>
<p>that the tibble <em>large.tracts</em> is grouped (<em>Groups: NAME [4]</em>). Use <code>ungroup()</code> to, well, ungroup the tibble.</p>
<pre class="r"><code>large.tracts %&gt;%
    group_by(NAME) %&gt;%
    ungroup()</code></pre>
<pre><code>## Simple feature collection with 825 features and 21 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: -123.0139 ymin: 32.53471 xmax: -116.9057 ymax: 37.86334
## geographic CRS: NAD83
## # A tibble: 825 x 22
##    GEOID.x   tpop pnhwhite19 pnhasn19 pnhblk19 phisp19 nhwhite nhasn nhblk  hisp
##    &lt;chr&gt;    &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 0607502…  4597      42.1     13.2     2.41    39.1     1937   606   111  1797
##  2 0607502…  4523      59.1     12.0     2.06    19.1     2675   542    93   864
##  3 0608551…  3020       9.11    40.6     4.11    37.5      275  1226   124  1134
##  4 0608550…  4373       2.72    35.3     1.14    59.5      119  1544    50  2604
##  5 0607300…  5271      53.1     36.1     0.247    5.92    2799  1902    13   312
##  6 0607300…  3726      61.8      2.44    1.29    32.0     2302    91    48  1191
##  7 0607300…  3344      66.4      3.71    3.23    23.3     2220   124   108   780
##  8 0607300…  2659      83.2      1.81    0.564   12.3     2211    48    15   328
##  9 0601900…  4750      19.2      2.74   13.4     63.9      911   130   637  3035
## 10 0601900…  3046      13.6     16.3     6.17    62.2      413   498   188  1894
## # … with 815 more rows, and 12 more variables: medinc19 &lt;dbl&gt;, rent19 &lt;dbl&gt;,
## #   houseval19 &lt;dbl&gt;, pcol19 &lt;dbl&gt;, GEOID.y &lt;chr&gt;, NAME &lt;chr&gt;,
## #   geometry &lt;MULTIPOLYGON [°]&gt;, nhwhitec &lt;dbl&gt;, nhasnc &lt;dbl&gt;, nhblkc &lt;dbl&gt;,
## #   hispc &lt;dbl&gt;, tpopc &lt;dbl&gt;</code></pre>
<p>and the grouping is gone! It’s always good practice to <code>ungroup()</code> a data set if you are saving it for future use (rather than using it as a summary table as we’ve doing so far in the class).</p>
<p>We’ve got the values for <span class="math inline">\(T_m\)</span>, <span class="math inline">\(T_k\)</span>, <span class="math inline">\(t_{im}\)</span>, and <span class="math inline">\(t_{ik}\)</span>, so we can calculate the rest of the formula, breaking it down piece-by-piece like we did in the handout and in Tuesday’s lecture. The following code calculates the Dissimilarity indices.</p>
<pre class="r"><code>large.tracts %&gt;%
      group_by(NAME) %&gt;%
      mutate(d.wb = abs(nhblk/nhblkc-nhwhite/nhwhitec),
              d.wa = abs(nhasn/nhasnc-nhwhite/nhwhitec), 
              d.wh = abs(hisp/hispc-nhwhite/nhwhitec)) %&gt;%
      summarize(BWD = 0.5*sum(d.wb, na.rm=TRUE), AWD = 0.5*sum(d.wa, na.rm=TRUE),
                HWD = 0.5*sum(d.wh, na.rm=TRUE)) %&gt;%
      ungroup()</code></pre>
<pre><code>## Simple feature collection with 4 features and 4 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: -123.0139 ymin: 32.53471 xmax: -116.9057 ymax: 37.86334
## geographic CRS: NAD83
## # A tibble: 4 x 5
##   NAME        BWD   AWD   HWD                                           geometry
##   &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;                                 &lt;MULTIPOLYGON [°]&gt;
## 1 Fresno    0.467 0.387 0.407 (((-119.7546 36.70596, -119.7545 36.70029, -119.7…
## 2 San Diego 0.556 0.468 0.537 (((-116.9537 32.56761, -116.9492 32.56768, -116.9…
## 3 San Fran… 0.526 0.399 0.431 (((-123.0139 37.70036, -123.0078 37.69894, -123.0…
## 4 San Jose  0.420 0.478 0.483 (((-121.6798 37.15859, -121.672 37.16406, -121.67…</code></pre>
<p><br></p>
<p>Let’s break the code down so we’re all on the same page. We use <code>mutate()</code> to calculate the tract level contributions to the index, i.e. the value <span class="math inline">\(\left|\frac{t_{rm}}{T_m} - \frac{t_{rk}}{T_k}\right|\)</span> for each neighborhood <span class="math inline">\(i\)</span>. Next, we turn to <code>summarize()</code> to finish the rest of the job. Within <code>summarize()</code>, we use the function <code>sum()</code> to add the neighborhood specific values in Equation 1 in Handout 8. In other words, <code>sum()</code> is performing the <span class="math inline">\(\sum\limits_{i}^{N}\)</span> that adds up <span class="math inline">\(\left|\frac{t_{rm}}{T_m} - \frac{t_{rk}}{T_k}\right|\)</span>. Finally, multiply the summed up value by 0.5 to get the final indices.</p>
<p><br></p>
<p>The resulting values provide the Dissimilarity indices for Black/White (<em>BWD</em>), Asian/White (<em>AWD</em>), and Hispanic/White (<em>HWD</em>). In all of these cases, we calculate segregation from white residents, but you can calculate segregation for any race/ethnicity combination (e.g. Black/Hispanic). Instead of just copying and pasting the chunk of code above into your console, make sure you understand what each line of code is doing. Not only will it help you become a more seasoned R coder, but it will also help you better understand the underlying math behind the Dissimilarity index.</p>
<p><br></p>
<p>The results table we got above is a little messy. Let’s clean it up by doing two things: (1) Drop the geometry column using <code>st_drop_geometry()</code>, which is a part of the <strong>sf</strong> package, and (2) use the <code>kable()</code> function, which is a part of the <strong>knitr</strong> package, to make a nicely formatted table. We add these functions to the bottom of the code we ran directly above.</p>
<pre class="r"><code>large.tracts %&gt;%
      group_by(NAME) %&gt;%
      mutate(d.wb = abs(nhblk/nhblkc-nhwhite/nhwhitec),
              d.wa = abs(nhasn/nhasnc-nhwhite/nhwhitec), 
              d.wh = abs(hisp/hispc-nhwhite/nhwhitec)) %&gt;%
      summarize(BWD = 0.5*sum(d.wb, na.rm=TRUE), AWD = 0.5*sum(d.wa, na.rm=TRUE),
                HWD = 0.5*sum(d.wh, na.rm=TRUE)) %&gt;%
      ungroup() %&gt;%
      st_drop_geometry() %&gt;%
      kable(digits = 3)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">NAME</th>
<th align="right">BWD</th>
<th align="right">AWD</th>
<th align="right">HWD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Fresno</td>
<td align="right">0.467</td>
<td align="right">0.387</td>
<td align="right">0.407</td>
</tr>
<tr class="even">
<td align="left">San Diego</td>
<td align="right">0.556</td>
<td align="right">0.468</td>
<td align="right">0.537</td>
</tr>
<tr class="odd">
<td align="left">San Francisco</td>
<td align="right">0.526</td>
<td align="right">0.399</td>
<td align="right">0.431</td>
</tr>
<tr class="even">
<td align="left">San Jose</td>
<td align="right">0.420</td>
<td align="right">0.478</td>
<td align="right">0.483</td>
</tr>
</tbody>
</table>
<p>Looks much better. The argument <code>digits = 3</code> within <code>kable()</code> rounds up values to three significant digits after the decimal.</p>
<p>The Dissimilarity index for Black/White in Fresno is 0.467. The interpretation of this value is that 46.7% of black residents would need to move neighborhoods in order to achieve a uniform distribution of black and white residents across neighborhoods in the city.</p>
<div style="margin-bottom:25px;">

</div>
</div>
</div>
<div id="gentrification" class="section level2">
<h2><strong>Gentrification</strong></h2>
<p><br />
</p>
<p>We go from one form of place-based inequality in segregation to another form in gentrification. How do we determine whether a neighborhood is undergoing gentrification? Let’s find out using a quantitative approach. We’ll determine which neighborhoods are experiencing gentrification in the City of Fresno, an issue that has gotten a lot of <a href="https://www.fresnobee.com/news/local/article222458970.html">local attention</a>.</p>
<p>Let’s first filter Fresno tracts from <em>large.tracts</em>.</p>
<pre class="r"><code>fresno.tracts &lt;- large.tracts %&gt;%
            filter(NAME == &quot;Fresno&quot;)</code></pre>
<div style="margin-bottom:25px;">

</div>
<div id="read-in-the-data-1" class="section level3">
<h3><strong>Read in the data</strong></h3>
<p><br />
</p>
<p>We will use the Ding et al. (2016) method outlined in Handout 8 for measuring gentrification. The measure defines gentrification as follows</p>
<ul>
<li>A neighborhood is eligible for gentrification if its median household income is less than the city’s median household income at the beginning of the observation period.</li>
<li>An eligible neighborhood gentrifies if its change from the beginning to the end of the observation period in median gross rent <em>or</em> median housing value is greater than the change in the city <em>and</em> the change in its percent of residents that have a college degree is more than the change in the city.</li>
</ul>
<p>We will define the beginning of the period using 2006-2010 ACS data (this is the first ACS period using 2010 tract boundaries) and the end of the period using 2015-2019 ACS data. We already downloaded the 2015-2019 ACS data on rent, housing values and percent college for census tracts. We will need to read in 2006-2010 tract-level median gross rent, median housing value and percent with a college degree. Notice that I attached a <em>10</em> to the end of each variable to signify that it is for 2006-2010. Also note that we don’t need any spatial data since <em>fresno.tracts</em> is already an <strong>sf</strong> object, so we don’t include the argument <code>geometry = TRUE</code>.</p>
<pre class="r"><code># Bring in 2006-2010 census tract data using the Census API 
ca.tracts10 &lt;- get_acs(geography = &quot;tract&quot;, 
              year = 2010,
              variables = c(medinc10 = &quot;B19013_001&quot;, rent10  = &quot;B25064_001&quot;,
                            houseval10 = &quot;B25077_001&quot;, bachm = &quot;B15002_015&quot;,
                            mastersm = &quot;B15002_016&quot;, profm = &quot;B15002_017&quot;,
                            phdm = &quot;B15002_018&quot;, bachf = &quot;B15002_032&quot;,
                            mastersf = &quot;B15002_033&quot;, proff = &quot;B15002_034&quot;,
                            phdf = &quot;B15002_035&quot;, totcol = &quot;B15002_001&quot;),
              state = &quot;CA&quot;,
              survey = &quot;acs5&quot;,
              output = &quot;wide&quot;)

# Make the data tidy, calculate and keep essential vars. 
ca.tracts10 &lt;- ca.tracts10 %&gt;% 
  rename_with(~ sub(&quot;E$&quot;, &quot;&quot;, .x), everything()) %&gt;%
  mutate(pcol10 = 100*(bachm+mastersm+profm+phdm+bachf+mastersf+proff+phdf)/totcol) %&gt;%
  select(c(GEOID,medinc10, rent10, houseval10, pcol10)) </code></pre>
<p><br></p>
<p>Note that you might get an error that states</p>
<pre><code>Calls: &lt;Anonymous&gt; ... withCallingHandlers -&gt; withVisible -&gt; eval -&gt; eval -&gt; get_acs
Execution halted</code></pre>
<p><br></p>
<p>Sometimes the Census API experiences a hiccup like above when downloading older data such as 2006-2010 ACS. My advice is to wait a few minutes (or more) and the run the code (or knit your file) again until the hiccup goes away.</p>
<p>As described in Handout 8, we need to compare neighborhoods to the entire City of Fresno This means we need to bring in city data for the beginning (2006-10) and end (2015-2019) periods. First, let’s bring in 2006-2010 ACS data for all places in California using <code>get_acs()</code>. We use the argument <code>geography = "place"</code>. We specify the data as place level 2006-2010 by attaching a <em>c10</em> to the end of each variable. No need for the spatial data, so we don’t include <code>geometry = TRUE</code> here.</p>
<pre class="r"><code># Bring in census tract data using the Census API 
ca.places10 &lt;- get_acs(geography = &quot;place&quot;, 
              year = 2010,
              variables = c(medincc10 = &quot;B19013_001&quot;, rentc10  = &quot;B25064_001&quot;,
                            housevalc10 = &quot;B25077_001&quot;, bachm = &quot;B15002_015&quot;,
                            mastersm = &quot;B15002_016&quot;, profm = &quot;B15002_017&quot;,
                            phdm = &quot;B15002_018&quot;, bachf = &quot;B15002_032&quot;,
                            mastersf = &quot;B15002_033&quot;, proff = &quot;B15002_034&quot;,
                            phdf = &quot;B15002_035&quot;, totcol = &quot;B15002_001&quot;),
              state = &quot;CA&quot;,
              survey = &quot;acs5&quot;,
              output = &quot;wide&quot;)

# Make the data tidy, calculate and keep essential vars. Also take out zero population tracts
ca.places10 &lt;- ca.places10 %&gt;% 
  rename_with(~ sub(&quot;E$&quot;, &quot;&quot;, .x), everything()) %&gt;%
  mutate(pcolc10 = 100*(bachm+mastersm+profm+phdm+bachf+mastersf+proff+phdf)/totcol) %&gt;%
  select(c(GEOID,medincc10, rentc10, housevalc10, pcolc10)) </code></pre>
<p><br></p>
<p>We next need to bring in current (2015-2019) place level data. We specify the data as place level 2015-2019 by attaching a <em>c19</em> to the end of each variable. No need for the spatial data, so we don’t include <code>geometry = TRUE</code> here.</p>
<pre class="r"><code># Bring in census tract data using the Census API 
ca.places19 &lt;- get_acs(geography = &quot;place&quot;, 
              year = 2019,
              variables = c(medincc19 = &quot;B19013_001&quot;, rentc19  = &quot;B25064_001&quot;,
                            housevalc19 = &quot;B25077_001&quot;, bachc = &quot;B15003_022&quot;,
                            mastersc = &quot;B15003_023&quot;, profc = &quot;B15003_024&quot;,
                            phdc = &quot;B15003_025&quot;, totcolc = &quot;B15003_001&quot;),
              state = &quot;CA&quot;,
              survey = &quot;acs5&quot;,
              output = &quot;wide&quot;)

# Make the data tidy, calculate and keep essential vars. Also take out zero population tracts
ca.places19 &lt;- ca.places19 %&gt;% 
  rename_with(~ sub(&quot;E$&quot;, &quot;&quot;, .x), everything()) %&gt;%
  mutate(pcolc19 = 100*(bachc+mastersc+profc+phdc)/totcolc) %&gt;%
  select(c(GEOID,medincc19, rentc19, housevalc19, pcolc19)) </code></pre>
<p>The <strong>sf</strong> object <em>fresno.tracts</em> contains 2015-2019 ACS tract-level data. We join <em>ca.tracts10</em>, which contains 2006-2010 ACS tract-level data, using <code>left_join()</code>. What are the IDs we need in order to join the two objects?</p>
<pre class="r"><code>names(fresno.tracts)</code></pre>
<pre><code>##  [1] &quot;GEOID.x&quot;    &quot;tpop&quot;       &quot;pnhwhite19&quot; &quot;pnhasn19&quot;   &quot;pnhblk19&quot;  
##  [6] &quot;phisp19&quot;    &quot;nhwhite&quot;    &quot;nhasn&quot;      &quot;nhblk&quot;      &quot;hisp&quot;      
## [11] &quot;medinc19&quot;   &quot;rent19&quot;     &quot;houseval19&quot; &quot;pcol19&quot;     &quot;GEOID.y&quot;   
## [16] &quot;NAME&quot;       &quot;geometry&quot;   &quot;nhwhitec&quot;   &quot;nhasnc&quot;     &quot;nhblkc&quot;    
## [21] &quot;hispc&quot;      &quot;tpopc&quot;</code></pre>
<pre class="r"><code>names(ca.tracts10)</code></pre>
<pre><code>## [1] &quot;GEOID&quot;      &quot;medinc10&quot;   &quot;rent10&quot;     &quot;houseval10&quot; &quot;pcol10&quot;</code></pre>
<p>The GEOID is <em>GEOID.x</em> in <em>fresno.tracts</em> and <em>GEOID</em> in <em>ca.tracts10</em></p>
<pre class="r"><code>fresno.tracts &lt;- fresno.tracts %&gt;%
            left_join(ca.tracts10, by = c(&quot;GEOID.x&quot; = &quot;GEOID&quot;))</code></pre>
<p>Next, we need to join <em>ca.places10</em> and <em>ca.places19</em>, which contain 2006-2010 and 2015-2019 Fresno city-level data, respectively, to <em>fresno.tracts</em>. What are the join IDs?</p>
<pre class="r"><code>names(fresno.tracts)</code></pre>
<pre><code>##  [1] &quot;GEOID.x&quot;    &quot;tpop&quot;       &quot;pnhwhite19&quot; &quot;pnhasn19&quot;   &quot;pnhblk19&quot;  
##  [6] &quot;phisp19&quot;    &quot;nhwhite&quot;    &quot;nhasn&quot;      &quot;nhblk&quot;      &quot;hisp&quot;      
## [11] &quot;medinc19&quot;   &quot;rent19&quot;     &quot;houseval19&quot; &quot;pcol19&quot;     &quot;GEOID.y&quot;   
## [16] &quot;NAME&quot;       &quot;geometry&quot;   &quot;nhwhitec&quot;   &quot;nhasnc&quot;     &quot;nhblkc&quot;    
## [21] &quot;hispc&quot;      &quot;tpopc&quot;      &quot;medinc10&quot;   &quot;rent10&quot;     &quot;houseval10&quot;
## [26] &quot;pcol10&quot;</code></pre>
<pre class="r"><code>names(ca.places10)</code></pre>
<pre><code>## [1] &quot;GEOID&quot;       &quot;medincc10&quot;   &quot;rentc10&quot;     &quot;housevalc10&quot; &quot;pcolc10&quot;</code></pre>
<pre class="r"><code>names(ca.places19)</code></pre>
<pre><code>## [1] &quot;GEOID&quot;       &quot;medincc19&quot;   &quot;rentc19&quot;     &quot;housevalc19&quot; &quot;pcolc19&quot;</code></pre>
<p>The city-level GEOID is <em>GEOID.y</em> in <em>fresno.tracts</em> and <em>GEOID</em> in both <em>ca.places10</em> and <em>ca.places19</em>.</p>
<pre class="r"><code>fresno.tracts &lt;- fresno.tracts %&gt;%
            left_join(ca.places10, by = c(&quot;GEOID.y&quot; = &quot;GEOID&quot;)) %&gt;%
            left_join(ca.places19, by = c(&quot;GEOID.y&quot; = &quot;GEOID&quot;)) </code></pre>
<p>Look at the data to make sure the joins went as expected.</p>
<pre class="r"><code>glimpse(fresno.tracts)</code></pre>
<p>We’re done!</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="gentrification-eligible-tracts" class="section level3">
<h3><strong>Gentrification eligible tracts</strong></h3>
<p><br />
</p>
<p>We’ve got all the data we need in one data object (<em>fresno.tracts</em>). Now we can start constructing our gentrification measure. First, let’s determine whether a tract is eligible to gentrify in the first place. A neighborhood is eligible for gentrification if its median household income is less than the city’s median household income in 2006-2010. We create a variable named <em>eligible</em> that specifies whether a neighborhood is eligible or not using the <code>ifelse()</code> function within <code>mutate()</code>.</p>
<pre class="r"><code>fresno.tracts &lt;- fresno.tracts %&gt;%
            mutate(eligible = ifelse(medinc10 &lt; medincc10, &quot;Eligible&quot;, &quot;Not Eligible&quot;))</code></pre>
<p>A neighborhood eligible to gentrify is given the label “Eligible”. What is the proportion of neighborhoods that are eligible to gentrify? Here, we are summarizing a categorical variable, which we covered in <a href="https://crd150.github.io/lab4.html#Categorical_variables">Lab 4</a>. Let’s put the results in a nice looking table by dropping the geometry using the function <code>st_drop_geometry()</code> and creating a nicely formatted table using the function <code>kable()</code>. We use the argument <code>digits = 2</code> to round the values to two significant digits after the decimal place.</p>
<pre class="r"><code>fresno.tracts %&gt;%
  group_by(eligible) %&gt;%
  summarize(n = n()) %&gt;%
  mutate(proportion = n / sum(n)) %&gt;%
  ungroup() %&gt;%
  st_drop_geometry() %&gt;%
  kable(digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">eligible</th>
<th align="right">n</th>
<th align="right">proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Eligible</td>
<td align="right">71</td>
<td align="right">0.57</td>
</tr>
<tr class="even">
<td align="left">Not Eligible</td>
<td align="right">52</td>
<td align="right">0.42</td>
</tr>
<tr class="odd">
<td align="left">NA</td>
<td align="right">1</td>
<td align="right">0.01</td>
</tr>
</tbody>
</table>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="gentrifying-tracts" class="section level3">
<h3><strong>Gentrifying tracts</strong></h3>
<p><br />
</p>
<p>An eligible neighborhood gentrifies if its change between 2006-2010 and 2015-2019 in median gross rent <em>or</em> median housing value is greater than the change in the city <em>and</em> the change in its percent of residents that have a college degree is more than the change in the city.</p>
<p>Let’s first calculate the tract-level differences in rent <em>rentch</em>, housing values <em>housech</em>, and percent with a college degree <em>pcolch</em>.</p>
<pre class="r"><code>fresno.tracts &lt;- fresno.tracts %&gt;%
            mutate(rentch = rent19-rent10, housech = houseval19-houseval10,
                   pcolch = pcol19-pcol10)</code></pre>
<p>Next, we calculate the city-level differences in rent <em>rentchc</em>, housing values <em>housechc</em>, and percent with a college degree <em>pcolchc</em>.</p>
<pre class="r"><code>fresno.tracts &lt;- fresno.tracts %&gt;%
            mutate(rentchc = rentc19-rentc10, housechc = housevalc19-housevalc10,
                   pcolchc = pcolc19-pcolc10)</code></pre>
<p>We now have all the pieces to construct a variable <em>gent</em> that labels tracts as “Not eligible”, “Gentrifying”, and “Not Gentrifying”. We do this using a set of <code>ifelse()</code> statements within <code>mutate()</code>.</p>
<pre class="r"><code>fresno.tracts &lt;- fresno.tracts %&gt;%
            mutate(gent = ifelse(eligible == &quot;Not Eligible&quot;, &quot;Not Eligible&quot;,
                          ifelse(eligible == &quot;Eligible&quot; &amp; pcolch &gt; pcolchc &amp;
                                (rentch &gt; rentchc | housech &gt; housechc), &quot;Gentrifying&quot;,
                                &quot;Not Gentrifying&quot;)))</code></pre>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="examining-gentrification" class="section level3">
<h3><strong>Examining Gentrification</strong></h3>
<p><br />
</p>
<p>What is the proportion of neighborhoods in Fresno that experienced gentrification? Let’s put it in a nice looking table by dropping the geometry using the function <code>st_drop_geometry()</code> and using the function <code>kable()</code>.</p>
<pre class="r"><code>fresno.tracts %&gt;%
  group_by(gent) %&gt;%
  summarize(n = n()) %&gt;%
  mutate(proportion = n / sum(n)) %&gt;%
  ungroup() %&gt;%
  st_drop_geometry() %&gt;%
  kable(digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">gent</th>
<th align="right">n</th>
<th align="right">proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Gentrifying</td>
<td align="right">22</td>
<td align="right">0.18</td>
</tr>
<tr class="even">
<td align="left">Not Eligible</td>
<td align="right">52</td>
<td align="right">0.42</td>
</tr>
<tr class="odd">
<td align="left">Not Gentrifying</td>
<td align="right">49</td>
<td align="right">0.40</td>
</tr>
<tr class="even">
<td align="left">NA</td>
<td align="right">1</td>
<td align="right">0.01</td>
</tr>
</tbody>
</table>
<p>Approximately 18 percent of neighborhoods in Fresno experienced gentrification between 2010 and 2019. Where are these neighborhoods located? Let’s make a nice color patch map using our best buddy <code>tm_shape()</code>.</p>
<pre class="r"><code>tm_shape(fresno.tracts, unit = &quot;mi&quot;) +
  tm_polygons(col = &quot;gent&quot;, style = &quot;cat&quot;,palette = &quot;Paired&quot;, border.alpha = 0,
              title = &quot;&quot;) +
  tm_scale_bar(breaks = c(0, 1, 2), text.size  = 0.75, position = c(&quot;right&quot;, &quot;bottom&quot;))  +
  tm_layout(main.title = &quot;2010-2019 Gentrification Status in Fresno&quot;, main.title.size = 0.95, frame = FALSE, legend.outside = TRUE)</code></pre>
<p>Several students indicated in the first day of class that they are from Fresno. Is your neighborhood gentrifying based on the measure we constructed above?</p>
<p>What is the racial/ethnic composition of gentrifying vs non-gentrifying neighborhoods? We are summarizing two variables, one categorical and the other numeric. We covered this in <a href="https://crd150.github.io/lab4.html#One_categorical,_one_numeric">Lab 4</a>. Here is a summary table showing mean 2019 race/ethnicity by gentrification status. Note that I removed the tracts missing gentrification status from the table using <code>filter()</code>.</p>
<pre class="r"><code>fresno.tracts %&gt;%
  filter(is.na(gent) == FALSE) %&gt;%
  group_by(gent) %&gt;%
  summarize(&quot;% White&quot; = mean(pnhwhite19),
            &quot;% Black&quot; = mean(pnhblk19),
            &quot;% Hispanic&quot; = mean(phisp19),
            &quot;% Asian&quot; = mean(pnhasn19)) %&gt;%
  st_drop_geometry() %&gt;%
  kable(digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">gent</th>
<th align="right">% White</th>
<th align="right">% Black</th>
<th align="right">% Hispanic</th>
<th align="right">% Asian</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Gentrifying</td>
<td align="right">15.86</td>
<td align="right">7.26</td>
<td align="right">63.41</td>
<td align="right">11.45</td>
</tr>
<tr class="even">
<td align="left">Not Eligible</td>
<td align="right">42.85</td>
<td align="right">4.55</td>
<td align="right">35.80</td>
<td align="right">13.55</td>
</tr>
<tr class="odd">
<td align="left">Not Gentrifying</td>
<td align="right">17.86</td>
<td align="right">8.15</td>
<td align="right">60.25</td>
<td align="right">10.83</td>
</tr>
</tbody>
</table>
<hr />
<p><a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.</p>
<p>Website created and maintained by <a href="https://nbrazil.faculty.ucdavis.edu/">Noli Brazil</a></p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "site_libs/mathjax-local/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
