---
title: "Syllabus"
subtitle: <h4 style="font-style:normal">CRD 150 - Quantitative Methods in Community Research</h4>
date: <h4 style="font-style:normal">Winter 2020</h4>
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    theme: cosmo
---


<style>
p.comment {
background-color: #DBDBDB;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: italic;
}

.figure {
   margin-top: 20px;
   margin-bottom: 20px;
}

h1.title {
  font-weight: bold;
  font-family: Arial;  
}

h2.title {
  font-family: Arial;  
}

</style>


<style type="text/css">
#TOC {
  font-size: 13px;
  font-family: Arial;
}
</style>

\

The following is an abridged version of the course syllabus.  A full course syllabus can be found on the Canvas class website.

<div style="margin-bottom:25px;">
</div>
## **Lecture and Lab Times**

* Lecture: 
    + Monday and Wednesday, 10:00-11:50 am, 204 Art
* Labs: 
    + Friday, 9:00-9:50 am, 2020 Science Lab
    + Friday, 10:00-10:50 am, 2020 Science Lab 

<div style="margin-bottom:25px;">
</div>
## **Instructor**

Dr. Noli Brazil  
*Contact*: nbrazil.at.ucdavis.edu  
*Office hours*: Monday from 4:00-5:30 pm or by appointment, in 2325 Hart Hall.  Please sign up for a slot [here](https://www.wejoinin.com/sheets/gsewa). Out of courtesy to other students, please do not sign up for more than two 15-minute blocks.  If you do, I will keep only the first two blocks.

<div style="margin-bottom:25px;">
</div>
## **Teaching Assistant**

Jake Dialesandro  
*Contact*: jdiales.at.ucdavis.edu  
*Office hours*: Wednesday: 12:00-2:00 pm, TBD

<div style="margin-bottom:25px;">
</div>
## **Course Objectives**

In this course, students will gain

* A foundation in critical thinking and reasoning skills based on data
* Skills in acquiring data from a wide range of reliable public and private sources 
* An understanding of the differences between spatial and nonspatial data
* Skills in data cleaning and management 
* An understanding of how to appropriately present nonspatial data in tables and graphs and spatial data in maps
* Skills in descriptive analysis of nonspatial and spatial data
* Proficiency in data analytic tools, specifically R
* An understanding of how these methods are employed in community research

<div style="margin-bottom:25px;">
</div>
## **Course Format**

The course is organized into two phases. 

* Part 1: Analyzing communities using nonspatial data.  Topics include descriptive statistics, exploratory data analysis, data presentation, and visualization.  As the major source of national community-level data in the United States, the U.S. Census will be covered extensively.    

* Part 2: Analyzing communities using spatial data. Topics include big data, government open data, participatory mapping, opportunity modelling, spatial clustering, residential segregation, and story mapping.

<div style="margin-bottom:25px;">
</div>
### **Lecture**

The Monday/Wednesday classes will be a combination of lecture, in-class computer mini labs, and exercises covering the week’s substantive topics.  For some lectures, I will ask you to bring your laptops to go through data acquisition examples and software program exercises.  I will also ask you to solve questions with pen and paper, usually in groups. The exercises during lecture are meant to be less about learning how to do a task in R, and more about deepening your understanding of the week’s substantive topics. 

<div style="margin-bottom:25px;">
</div>
### **Lab**

The Friday lab will provide hands on practice using real data.  Each lab will provide guides that will be released on the course website after the Wednesday lecture.  The guides will provide step-by-step instructions on executing specific tasks using a software program.  Although you do not need to turn in lab guides for a grade, it is expected that you will go through each guide and master its contents.  If the guides are released before the lab and are not due for a grade, then why attend lab?  Besides being mandatory, lab is where (1) the TA will go through higher level points and (2) you can get more refined feedback and help from the TA and your peers.  As such, it is to your benefit to come to lab having already gone through at least a portion of the lab guide, just like it is beneficial to come into lecture having read all the course readings assigned for that day. 


<div style="margin-bottom:25px;">
</div>
## **Required Readings**

Required reading material is composed of a combination of the following 

1.	Chapters from textbooks. 

There is no single official textbook for the course.  Instead, I’ve selected chapters from various textbooks, which I’ve scanned and uploaded onto Canvas.  

2.	Journal articles and research reports.

These are available on Canvas.  There are also occasional optional readings that provide applications of a method or a deeper look into a data source.

3.	My handouts

For some topics, in lieu of an article or book chapter, I will provide lecture handouts on Canvas in advance of the assigned class.  

<div style="margin-bottom:25px;">
</div>
## **Additional Readings**

The other major course material are lab guides, which will be released immediately after the Wednesday lecture.  Many of the R lab guides will closely follow two textbooks.  These textbooks are not required, but are great resources. 

The first textbook covers the first part of the course (nonspatial data)

* (RDS) Wickham, Hadley & Garret Grolemund. (2017). R for Data Science. Sebastopol, CA: O’Reilly Media.

The textbook is free online at: http://r4ds.had.co.nz/introduction.html  

The second textbook covers the second part of the course (spatial data)

* (GWR) Lovelace, Robin, Jakub Nowosad & Jannes Muenchow. (Forthcoming) Geocomputation with R. CRC Press.

The textbook is free online at: https://geocompr.robinlovelace.net/

<div style="margin-bottom:25px;">
</div>
## **Course Software**

[R](https://www.r-project.org/) is the only statistical language used in this course, as it has become an increasingly popular program for data analysis in the social sciences.  R is freeware and you can download it on your personal laptop and desktop computers.  We will use [RStudio](https://www.rstudio.com/) as a user friendly interface for R.  Lab computers will also have R and RStudio.  

We will also introduce the  programs [QGIS](https://qgis.org/en/site/) and [ArcGIS Online Story Maps](https://storymaps.arcgis.com/).

<div style="margin-bottom:25px;">
</div>
## **Course Requirements** 

1. Assignments (35%)

Assignments will be released on the lab website each week at the beginning of lab and will be due the following week on Canvas.  Assignment questions are located at the end of each lab guide. They will contain a combination of programming tasks and theoretical questions that you will need to answer on your own.  For each assignment, you will need to submit an R Markdown Rmd and html file on Canvas.  Complete assignment guidelines can be found [here](https://crd150.github.io/hw_guidelines.html).  If you get stuck you can seek help from the TA, who will be available in the scheduled lab sessions and during office hours.  We also encourage you to work with other students, **but you must submit your own assignment**.  

Late submissions will be deducted 10% per 24 hours until 72 hours after the submission due time.  After 72 hours your submission will not be graded.  No exception unless you provide documentation of your illness or bereavement before the due date.  If you cannot upload the assignment on Canvas due to technical issues, you must email it as an attachment to the TA by the submission due time.


2. Midterm exam (25%)

There will be a comprehensive in-class midterm examination that will test conceptual material covered in lecture, readings and lab.  The exam will be written and will consist of hand-written computational, multiple choice and short answer questions.  You will not be expected to write or interpret code. See the full syllabus and the Canvas exam folder for more information.

3. Final course project (35%)

The purpose of the final course project is to provide students the opportunity to apply the concepts and methods learned in class on a real-world problem of their choice.  The project is an individual project.  The project will involve choosing at least one specific community (city or county) and answering a question about that community. It will be completed in phases, which are designed to ensure progress throughout the quarter.  See the full syllabus and the Canvas final project folder for detailed information.

4. Class participation/attendance (5%)

Attendance in all classes and labs are required. However, we will not take attendance.  We will take note of a substantial number of absences. If you miss a class it is your responsibility to get the lecture/lab notes from classmates. You are expected to stay until the end of lecture and lab. If you need to leave early, please confirm with us at the beginning of lecture and sit somewhere where your departure will be minimally disruptive. Note that I will be introducing material in lecture that extends material covered in the readings.  You will be responsible for understanding this extended material for assignments and the midterm. Also note that given the class size I will know each of your names.  This means don’t take the 5% class attendance/participation lightly as that can sway your grade one way or another.

<div style="margin-bottom:25px;">
</div>	
## **Other Information**
\

Please see the full syllabus on the Canvas website for information regarding course communication, code of conduct, and grades.

<div style="margin-bottom:25px;">
</div>	
## **Course Agenda**
\

The schedule is subject to revision throughout the quarter.  Please see the full syllabus for a more detailed version of the agenda. *This lecture has optional readings. See full syllabus.

```{r echo=  FALSE, warning = FALSE, message = FALSE}
options(knitr.kable.NA = '')
library(knitr)
library(kableExtra)
library(sf)
library(tidyverse)
dt <- read_csv("/Users/noli/Documents/UCD/teaching/CRD150/Lab/crd150.github.io/agenda.csv")
kable(dt) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>%
    column_spec(1, width = "5em") %>%
    column_spec(4, width = "13em")
```


***


Website created and maintained by [Noli Brazil](https://nbrazil.faculty.ucdavis.edu/)